# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_qm_input.ui'
#
# Created: Tue Sep  3 19:15:24 2013
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_qm_input(object):
    def setupUi(self, qm_input):
        qm_input.setObjectName(_fromUtf8("qm_input"))
        qm_input.resize(654, 674)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(qm_input.sizePolicy().hasHeightForWidth())
        qm_input.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/qm_icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        qm_input.setWindowIcon(icon)
        self.verticalLayoutWidget_2 = QtGui.QWidget(qm_input)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 631, 62))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.vlOutputDir = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.vlOutputDir.setMargin(0)
        self.vlOutputDir.setObjectName(_fromUtf8("vlOutputDir"))
        self.lblOutputDirectory = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.lblOutputDirectory.setObjectName(_fromUtf8("lblOutputDirectory"))
        self.vlOutputDir.addWidget(self.lblOutputDirectory)
        self._2 = QtGui.QHBoxLayout()
        self._2.setObjectName(_fromUtf8("_2"))
        self.leScenarioDirectory = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        self.leScenarioDirectory.setReadOnly(True)
        self.leScenarioDirectory.setObjectName(_fromUtf8("leScenarioDirectory"))
        self._2.addWidget(self.leScenarioDirectory)
        self.pbScenarioDirectory = QtGui.QToolButton(self.verticalLayoutWidget_2)
        self.pbScenarioDirectory.setObjectName(_fromUtf8("pbScenarioDirectory"))
        self._2.addWidget(self.pbScenarioDirectory)
        self.vlOutputDir.addLayout(self._2)
        self.layoutWidget = QtGui.QWidget(qm_input)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 630, 621, 33))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.hlActions = QtGui.QHBoxLayout(self.layoutWidget)
        self.hlActions.setMargin(0)
        self.hlActions.setObjectName(_fromUtf8("hlActions"))
        self.progressBar = QtGui.QProgressBar(self.layoutWidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.hlActions.addWidget(self.progressBar)
        self.buttonBox = QtGui.QDialogButtonBox(self.layoutWidget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.hlActions.addWidget(self.buttonBox)
        self.tabWidget = QtGui.QTabWidget(qm_input)
        self.tabWidget.setGeometry(QtCore.QRect(10, 80, 631, 541))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabGeneral = QtGui.QWidget()
        self.tabGeneral.setObjectName(_fromUtf8("tabGeneral"))
        self.verticalLayoutWidget_4 = QtGui.QWidget(self.tabGeneral)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(10, 0, 540, 501))
        self.verticalLayoutWidget_4.setObjectName(_fromUtf8("verticalLayoutWidget_4"))
        self.vlGeneral = QtGui.QVBoxLayout(self.verticalLayoutWidget_4)
        self.vlGeneral.setMargin(0)
        self.vlGeneral.setObjectName(_fromUtf8("vlGeneral"))
        self.lblVERSION = QtGui.QLabel(self.verticalLayoutWidget_4)
        self.lblVERSION.setObjectName(_fromUtf8("lblVERSION"))
        self.vlGeneral.addWidget(self.lblVERSION)
        self.leVERSION = QtGui.QLineEdit(self.verticalLayoutWidget_4)
        self.leVERSION.setObjectName(_fromUtf8("leVERSION"))
        self.vlGeneral.addWidget(self.leVERSION)
        self.lblBLM = QtGui.QLabel(self.verticalLayoutWidget_4)
        self.lblBLM.setObjectName(_fromUtf8("lblBLM"))
        self.vlGeneral.addWidget(self.lblBLM)
        self.spnBLM = QtGui.QDoubleSpinBox(self.verticalLayoutWidget_4)
        self.spnBLM.setEnabled(True)
        self.spnBLM.setDecimals(6)
        self.spnBLM.setMinimum(0.0)
        self.spnBLM.setMaximum(1000000000.0)
        self.spnBLM.setSingleStep(1e-06)
        self.spnBLM.setProperty("value", 1.0)
        self.spnBLM.setObjectName(_fromUtf8("spnBLM"))
        self.vlGeneral.addWidget(self.spnBLM)
        self.lblMISSLEVEL = QtGui.QLabel(self.verticalLayoutWidget_4)
        self.lblMISSLEVEL.setObjectName(_fromUtf8("lblMISSLEVEL"))
        self.vlGeneral.addWidget(self.lblMISSLEVEL)
        self.spnMISSLEVEL = QtGui.QDoubleSpinBox(self.verticalLayoutWidget_4)
        self.spnMISSLEVEL.setMaximum(1.0)
        self.spnMISSLEVEL.setSingleStep(0.05)
        self.spnMISSLEVEL.setProperty("value", 0.95)
        self.spnMISSLEVEL.setObjectName(_fromUtf8("spnMISSLEVEL"))
        self.vlGeneral.addWidget(self.spnMISSLEVEL)
        self.lblPROP = QtGui.QLabel(self.verticalLayoutWidget_4)
        self.lblPROP.setObjectName(_fromUtf8("lblPROP"))
        self.vlGeneral.addWidget(self.lblPROP)
        self.spnPROP = QtGui.QDoubleSpinBox(self.verticalLayoutWidget_4)
        self.spnPROP.setEnabled(True)
        self.spnPROP.setDecimals(2)
        self.spnPROP.setMinimum(0.0)
        self.spnPROP.setMaximum(1.0)
        self.spnPROP.setSingleStep(0.05)
        self.spnPROP.setProperty("value", 0.5)
        self.spnPROP.setObjectName(_fromUtf8("spnPROP"))
        self.vlGeneral.addWidget(self.spnPROP)
        self.lblNUMREPS = QtGui.QLabel(self.verticalLayoutWidget_4)
        self.lblNUMREPS.setObjectName(_fromUtf8("lblNUMREPS"))
        self.vlGeneral.addWidget(self.lblNUMREPS)
        self.spnNUMREPS = QtGui.QDoubleSpinBox(self.verticalLayoutWidget_4)
        self.spnNUMREPS.setEnabled(True)
        self.spnNUMREPS.setDecimals(0)
        self.spnNUMREPS.setMinimum(1.0)
        self.spnNUMREPS.setMaximum(1000000000.0)
        self.spnNUMREPS.setSingleStep(10.0)
        self.spnNUMREPS.setProperty("value", 10.0)
        self.spnNUMREPS.setObjectName(_fromUtf8("spnNUMREPS"))
        self.vlGeneral.addWidget(self.spnNUMREPS)
        self.lblCLUMPTYPE = QtGui.QLabel(self.verticalLayoutWidget_4)
        self.lblCLUMPTYPE.setObjectName(_fromUtf8("lblCLUMPTYPE"))
        self.vlGeneral.addWidget(self.lblCLUMPTYPE)
        self.cbxCLUMPTYPE = QtGui.QComboBox(self.verticalLayoutWidget_4)
        self.cbxCLUMPTYPE.setObjectName(_fromUtf8("cbxCLUMPTYPE"))
        self.cbxCLUMPTYPE.addItem(_fromUtf8(""))
        self.cbxCLUMPTYPE.addItem(_fromUtf8(""))
        self.cbxCLUMPTYPE.addItem(_fromUtf8(""))
        self.vlGeneral.addWidget(self.cbxCLUMPTYPE)
        self.lblRANDSEED = QtGui.QLabel(self.verticalLayoutWidget_4)
        self.lblRANDSEED.setObjectName(_fromUtf8("lblRANDSEED"))
        self.vlGeneral.addWidget(self.lblRANDSEED)
        self.spnRANDSEED = QtGui.QDoubleSpinBox(self.verticalLayoutWidget_4)
        self.spnRANDSEED.setEnabled(True)
        self.spnRANDSEED.setDecimals(0)
        self.spnRANDSEED.setMinimum(-1.0)
        self.spnRANDSEED.setMaximum(1000000000.0)
        self.spnRANDSEED.setSingleStep(1.0)
        self.spnRANDSEED.setProperty("value", -1.0)
        self.spnRANDSEED.setObjectName(_fromUtf8("spnRANDSEED"))
        self.vlGeneral.addWidget(self.spnRANDSEED)
        self.lblBESTSCORE = QtGui.QLabel(self.verticalLayoutWidget_4)
        self.lblBESTSCORE.setObjectName(_fromUtf8("lblBESTSCORE"))
        self.vlGeneral.addWidget(self.lblBESTSCORE)
        self.spnBESTSCORE = QtGui.QDoubleSpinBox(self.verticalLayoutWidget_4)
        self.spnBESTSCORE.setEnabled(True)
        self.spnBESTSCORE.setDecimals(0)
        self.spnBESTSCORE.setMinimum(-1.0)
        self.spnBESTSCORE.setMaximum(1000000000.0)
        self.spnBESTSCORE.setSingleStep(1.0)
        self.spnBESTSCORE.setProperty("value", -1.0)
        self.spnBESTSCORE.setObjectName(_fromUtf8("spnBESTSCORE"))
        self.vlGeneral.addWidget(self.spnBESTSCORE)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vlGeneral.addItem(spacerItem)
        self.tabWidget.addTab(self.tabGeneral, _fromUtf8(""))
        self.tabRun = QtGui.QWidget()
        self.tabRun.setAccessibleName(_fromUtf8(""))
        self.tabRun.setObjectName(_fromUtf8("tabRun"))
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.tabRun)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 0, 511, 501))
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self.vlAnnealing = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.vlAnnealing.setMargin(0)
        self.vlAnnealing.setObjectName(_fromUtf8("vlAnnealing"))
        self.lblNUMITNS = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.lblNUMITNS.setObjectName(_fromUtf8("lblNUMITNS"))
        self.vlAnnealing.addWidget(self.lblNUMITNS)
        self.spnNUMITNS = QtGui.QDoubleSpinBox(self.verticalLayoutWidget_3)
        self.spnNUMITNS.setEnabled(True)
        self.spnNUMITNS.setDecimals(0)
        self.spnNUMITNS.setMinimum(1.0)
        self.spnNUMITNS.setMaximum(1000000000.0)
        self.spnNUMITNS.setSingleStep(100000.0)
        self.spnNUMITNS.setProperty("value", 1000000.0)
        self.spnNUMITNS.setObjectName(_fromUtf8("spnNUMITNS"))
        self.vlAnnealing.addWidget(self.spnNUMITNS)
        self.lblNUMTEMP = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.lblNUMTEMP.setObjectName(_fromUtf8("lblNUMTEMP"))
        self.vlAnnealing.addWidget(self.lblNUMTEMP)
        self.spnNUMTEMP = QtGui.QDoubleSpinBox(self.verticalLayoutWidget_3)
        self.spnNUMTEMP.setEnabled(True)
        self.spnNUMTEMP.setDecimals(0)
        self.spnNUMTEMP.setMinimum(1.0)
        self.spnNUMTEMP.setMaximum(1000000000.0)
        self.spnNUMTEMP.setSingleStep(1000.0)
        self.spnNUMTEMP.setProperty("value", 10000.0)
        self.spnNUMTEMP.setObjectName(_fromUtf8("spnNUMTEMP"))
        self.vlAnnealing.addWidget(self.spnNUMTEMP)
        self.lblRUNMODE = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.lblRUNMODE.setObjectName(_fromUtf8("lblRUNMODE"))
        self.vlAnnealing.addWidget(self.lblRUNMODE)
        self.cbxRUNMODE = QtGui.QComboBox(self.verticalLayoutWidget_3)
        self.cbxRUNMODE.setObjectName(_fromUtf8("cbxRUNMODE"))
        self.cbxRUNMODE.addItem(_fromUtf8(""))
        self.cbxRUNMODE.addItem(_fromUtf8(""))
        self.cbxRUNMODE.addItem(_fromUtf8(""))
        self.cbxRUNMODE.addItem(_fromUtf8(""))
        self.cbxRUNMODE.addItem(_fromUtf8(""))
        self.cbxRUNMODE.addItem(_fromUtf8(""))
        self.cbxRUNMODE.addItem(_fromUtf8(""))
        self.cbxRUNMODE.addItem(_fromUtf8(""))
        self.vlAnnealing.addWidget(self.cbxRUNMODE)
        self.lblHEURTYPE = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.lblHEURTYPE.setEnabled(False)
        self.lblHEURTYPE.setObjectName(_fromUtf8("lblHEURTYPE"))
        self.vlAnnealing.addWidget(self.lblHEURTYPE)
        self.cbxHEURTYPE = QtGui.QComboBox(self.verticalLayoutWidget_3)
        self.cbxHEURTYPE.setEnabled(False)
        self.cbxHEURTYPE.setObjectName(_fromUtf8("cbxHEURTYPE"))
        self.cbxHEURTYPE.addItem(_fromUtf8(""))
        self.cbxHEURTYPE.addItem(_fromUtf8(""))
        self.cbxHEURTYPE.addItem(_fromUtf8(""))
        self.cbxHEURTYPE.addItem(_fromUtf8(""))
        self.cbxHEURTYPE.addItem(_fromUtf8(""))
        self.cbxHEURTYPE.addItem(_fromUtf8(""))
        self.cbxHEURTYPE.addItem(_fromUtf8(""))
        self.cbxHEURTYPE.addItem(_fromUtf8(""))
        self.vlAnnealing.addWidget(self.cbxHEURTYPE)
        self.lblITIMPTYPE = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.lblITIMPTYPE.setObjectName(_fromUtf8("lblITIMPTYPE"))
        self.vlAnnealing.addWidget(self.lblITIMPTYPE)
        self.cbxITIMPTYPE = QtGui.QComboBox(self.verticalLayoutWidget_3)
        self.cbxITIMPTYPE.setObjectName(_fromUtf8("cbxITIMPTYPE"))
        self.cbxITIMPTYPE.addItem(_fromUtf8(""))
        self.cbxITIMPTYPE.addItem(_fromUtf8(""))
        self.cbxITIMPTYPE.addItem(_fromUtf8(""))
        self.cbxITIMPTYPE.addItem(_fromUtf8(""))
        self.vlAnnealing.addWidget(self.cbxITIMPTYPE)
        self.lblSTARTTEMP = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.lblSTARTTEMP.setEnabled(True)
        self.lblSTARTTEMP.setObjectName(_fromUtf8("lblSTARTTEMP"))
        self.vlAnnealing.addWidget(self.lblSTARTTEMP)
        self.spnSTARTTEMP = QtGui.QDoubleSpinBox(self.verticalLayoutWidget_3)
        self.spnSTARTTEMP.setEnabled(True)
        self.spnSTARTTEMP.setDecimals(0)
        self.spnSTARTTEMP.setMinimum(-1.0)
        self.spnSTARTTEMP.setMaximum(1000000000.0)
        self.spnSTARTTEMP.setSingleStep(1.0)
        self.spnSTARTTEMP.setProperty("value", -1.0)
        self.spnSTARTTEMP.setObjectName(_fromUtf8("spnSTARTTEMP"))
        self.vlAnnealing.addWidget(self.spnSTARTTEMP)
        self.lblCOOLFAC = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.lblCOOLFAC.setEnabled(True)
        self.lblCOOLFAC.setObjectName(_fromUtf8("lblCOOLFAC"))
        self.vlAnnealing.addWidget(self.lblCOOLFAC)
        self.spnCOOLFAC = QtGui.QDoubleSpinBox(self.verticalLayoutWidget_3)
        self.spnCOOLFAC.setEnabled(True)
        self.spnCOOLFAC.setMaximum(1.0)
        self.spnCOOLFAC.setSingleStep(0.05)
        self.spnCOOLFAC.setObjectName(_fromUtf8("spnCOOLFAC"))
        self.vlAnnealing.addWidget(self.spnCOOLFAC)
        self.lblVERBOSITY = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.lblVERBOSITY.setObjectName(_fromUtf8("lblVERBOSITY"))
        self.vlAnnealing.addWidget(self.lblVERBOSITY)
        self.cbxVERBOSITY = QtGui.QComboBox(self.verticalLayoutWidget_3)
        self.cbxVERBOSITY.setObjectName(_fromUtf8("cbxVERBOSITY"))
        self.cbxVERBOSITY.addItem(_fromUtf8(""))
        self.cbxVERBOSITY.addItem(_fromUtf8(""))
        self.cbxVERBOSITY.addItem(_fromUtf8(""))
        self.cbxVERBOSITY.addItem(_fromUtf8(""))
        self.vlAnnealing.addWidget(self.cbxVERBOSITY)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vlAnnealing.addItem(spacerItem1)
        self.tabWidget.addTab(self.tabRun, _fromUtf8(""))
        self.tabInput = QtGui.QWidget()
        self.tabInput.setObjectName(_fromUtf8("tabInput"))
        self.verticalLayoutWidget_7 = QtGui.QWidget(self.tabInput)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(10, 10, 611, 321))
        self.verticalLayoutWidget_7.setObjectName(_fromUtf8("verticalLayoutWidget_7"))
        self.vlInputFiles = QtGui.QVBoxLayout(self.verticalLayoutWidget_7)
        self.vlInputFiles.setMargin(0)
        self.vlInputFiles.setObjectName(_fromUtf8("vlInputFiles"))
        self.hlInputFiles = QtGui.QHBoxLayout()
        self.hlInputFiles.setObjectName(_fromUtf8("hlInputFiles"))
        self.vlInput = QtGui.QVBoxLayout()
        self.vlInput.setObjectName(_fromUtf8("vlInput"))
        self.lbINPUTDIR = QtGui.QLabel(self.verticalLayoutWidget_7)
        self.lbINPUTDIR.setObjectName(_fromUtf8("lbINPUTDIR"))
        self.vlInput.addWidget(self.lbINPUTDIR)
        self.hlINPUTDIR = QtGui.QHBoxLayout()
        self.hlINPUTDIR.setObjectName(_fromUtf8("hlINPUTDIR"))
        self.leINPUTDIR = QtGui.QLineEdit(self.verticalLayoutWidget_7)
        self.leINPUTDIR.setText(_fromUtf8(""))
        self.leINPUTDIR.setReadOnly(True)
        self.leINPUTDIR.setObjectName(_fromUtf8("leINPUTDIR"))
        self.hlINPUTDIR.addWidget(self.leINPUTDIR)
        self.pbINPUTDIR = QtGui.QToolButton(self.verticalLayoutWidget_7)
        self.pbINPUTDIR.setObjectName(_fromUtf8("pbINPUTDIR"))
        self.hlINPUTDIR.addWidget(self.pbINPUTDIR)
        self.vlInput.addLayout(self.hlINPUTDIR)
        self.lblOUTPUTDIR = QtGui.QLabel(self.verticalLayoutWidget_7)
        self.lblOUTPUTDIR.setObjectName(_fromUtf8("lblOUTPUTDIR"))
        self.vlInput.addWidget(self.lblOUTPUTDIR)
        self.hlOUTPUTDIR = QtGui.QHBoxLayout()
        self.hlOUTPUTDIR.setObjectName(_fromUtf8("hlOUTPUTDIR"))
        self.leOUTPUTDIR = QtGui.QLineEdit(self.verticalLayoutWidget_7)
        self.leOUTPUTDIR.setText(_fromUtf8(""))
        self.leOUTPUTDIR.setReadOnly(True)
        self.leOUTPUTDIR.setObjectName(_fromUtf8("leOUTPUTDIR"))
        self.hlOUTPUTDIR.addWidget(self.leOUTPUTDIR)
        self.pbOUTPUTDIR = QtGui.QToolButton(self.verticalLayoutWidget_7)
        self.pbOUTPUTDIR.setObjectName(_fromUtf8("pbOUTPUTDIR"))
        self.hlOUTPUTDIR.addWidget(self.pbOUTPUTDIR)
        self.vlInput.addLayout(self.hlOUTPUTDIR)
        self.lblSPECNAME = QtGui.QLabel(self.verticalLayoutWidget_7)
        self.lblSPECNAME.setObjectName(_fromUtf8("lblSPECNAME"))
        self.vlInput.addWidget(self.lblSPECNAME)
        self.hlSPECNAME = QtGui.QHBoxLayout()
        self.hlSPECNAME.setObjectName(_fromUtf8("hlSPECNAME"))
        self.leSPECNAME = QtGui.QLineEdit(self.verticalLayoutWidget_7)
        self.leSPECNAME.setText(_fromUtf8(""))
        self.leSPECNAME.setReadOnly(True)
        self.leSPECNAME.setObjectName(_fromUtf8("leSPECNAME"))
        self.hlSPECNAME.addWidget(self.leSPECNAME)
        self.pbSPECNAME = QtGui.QToolButton(self.verticalLayoutWidget_7)
        self.pbSPECNAME.setObjectName(_fromUtf8("pbSPECNAME"))
        self.hlSPECNAME.addWidget(self.pbSPECNAME)
        self.vlInput.addLayout(self.hlSPECNAME)
        self.lblPUNAME = QtGui.QLabel(self.verticalLayoutWidget_7)
        self.lblPUNAME.setObjectName(_fromUtf8("lblPUNAME"))
        self.vlInput.addWidget(self.lblPUNAME)
        self.hlPUNAME = QtGui.QHBoxLayout()
        self.hlPUNAME.setObjectName(_fromUtf8("hlPUNAME"))
        self.lePUNAME = QtGui.QLineEdit(self.verticalLayoutWidget_7)
        self.lePUNAME.setText(_fromUtf8(""))
        self.lePUNAME.setReadOnly(True)
        self.lePUNAME.setObjectName(_fromUtf8("lePUNAME"))
        self.hlPUNAME.addWidget(self.lePUNAME)
        self.pbPUNAME = QtGui.QToolButton(self.verticalLayoutWidget_7)
        self.pbPUNAME.setObjectName(_fromUtf8("pbPUNAME"))
        self.hlPUNAME.addWidget(self.pbPUNAME)
        self.vlInput.addLayout(self.hlPUNAME)
        self.hlInputFiles.addLayout(self.vlInput)
        self.vlInputRight = QtGui.QVBoxLayout()
        self.vlInputRight.setObjectName(_fromUtf8("vlInputRight"))
        self.lblBOUNDNAME = QtGui.QLabel(self.verticalLayoutWidget_7)
        self.lblBOUNDNAME.setObjectName(_fromUtf8("lblBOUNDNAME"))
        self.vlInputRight.addWidget(self.lblBOUNDNAME)
        self.hlBOUNDNAME = QtGui.QHBoxLayout()
        self.hlBOUNDNAME.setObjectName(_fromUtf8("hlBOUNDNAME"))
        self.leBOUNDNAME = QtGui.QLineEdit(self.verticalLayoutWidget_7)
        self.leBOUNDNAME.setText(_fromUtf8(""))
        self.leBOUNDNAME.setReadOnly(True)
        self.leBOUNDNAME.setObjectName(_fromUtf8("leBOUNDNAME"))
        self.hlBOUNDNAME.addWidget(self.leBOUNDNAME)
        self.pbBOUNDNAME = QtGui.QToolButton(self.verticalLayoutWidget_7)
        self.pbBOUNDNAME.setObjectName(_fromUtf8("pbBOUNDNAME"))
        self.hlBOUNDNAME.addWidget(self.pbBOUNDNAME)
        self.vlInputRight.addLayout(self.hlBOUNDNAME)
        self.lblPUVSPRNAME = QtGui.QLabel(self.verticalLayoutWidget_7)
        self.lblPUVSPRNAME.setObjectName(_fromUtf8("lblPUVSPRNAME"))
        self.vlInputRight.addWidget(self.lblPUVSPRNAME)
        self.hlPUVSPRNAME = QtGui.QHBoxLayout()
        self.hlPUVSPRNAME.setObjectName(_fromUtf8("hlPUVSPRNAME"))
        self.lePUVSPRNAME = QtGui.QLineEdit(self.verticalLayoutWidget_7)
        self.lePUVSPRNAME.setText(_fromUtf8(""))
        self.lePUVSPRNAME.setReadOnly(True)
        self.lePUVSPRNAME.setObjectName(_fromUtf8("lePUVSPRNAME"))
        self.hlPUVSPRNAME.addWidget(self.lePUVSPRNAME)
        self.pbPUVSPRNAME = QtGui.QToolButton(self.verticalLayoutWidget_7)
        self.pbPUVSPRNAME.setObjectName(_fromUtf8("pbPUVSPRNAME"))
        self.hlPUVSPRNAME.addWidget(self.pbPUVSPRNAME)
        self.vlInputRight.addLayout(self.hlPUVSPRNAME)
        self.lblBLOCKDEFNAME = QtGui.QLabel(self.verticalLayoutWidget_7)
        self.lblBLOCKDEFNAME.setObjectName(_fromUtf8("lblBLOCKDEFNAME"))
        self.vlInputRight.addWidget(self.lblBLOCKDEFNAME)
        self.hlBLOCKDEFNAME = QtGui.QHBoxLayout()
        self.hlBLOCKDEFNAME.setObjectName(_fromUtf8("hlBLOCKDEFNAME"))
        self.leBLOCKDEFNAME = QtGui.QLineEdit(self.verticalLayoutWidget_7)
        self.leBLOCKDEFNAME.setText(_fromUtf8(""))
        self.leBLOCKDEFNAME.setReadOnly(True)
        self.leBLOCKDEFNAME.setObjectName(_fromUtf8("leBLOCKDEFNAME"))
        self.hlBLOCKDEFNAME.addWidget(self.leBLOCKDEFNAME)
        self.pbBLOCKDEFNAME = QtGui.QToolButton(self.verticalLayoutWidget_7)
        self.pbBLOCKDEFNAME.setObjectName(_fromUtf8("pbBLOCKDEFNAME"))
        self.hlBLOCKDEFNAME.addWidget(self.pbBLOCKDEFNAME)
        self.vlInputRight.addLayout(self.hlBLOCKDEFNAME)
        self.hlInputFiles.addLayout(self.vlInputRight)
        self.vlInputFiles.addLayout(self.hlInputFiles)
        self.lblMATRIXSPORDERNAME = QtGui.QLabel(self.verticalLayoutWidget_7)
        self.lblMATRIXSPORDERNAME.setObjectName(_fromUtf8("lblMATRIXSPORDERNAME"))
        self.vlInputFiles.addWidget(self.lblMATRIXSPORDERNAME)
        self.hlMATRIXSPORDERNAME = QtGui.QHBoxLayout()
        self.hlMATRIXSPORDERNAME.setObjectName(_fromUtf8("hlMATRIXSPORDERNAME"))
        self.leMATRIXSPORDERNAME = QtGui.QLineEdit(self.verticalLayoutWidget_7)
        self.leMATRIXSPORDERNAME.setText(_fromUtf8(""))
        self.leMATRIXSPORDERNAME.setReadOnly(True)
        self.leMATRIXSPORDERNAME.setObjectName(_fromUtf8("leMATRIXSPORDERNAME"))
        self.hlMATRIXSPORDERNAME.addWidget(self.leMATRIXSPORDERNAME)
        self.pbMATRIXSPORDERNAME = QtGui.QToolButton(self.verticalLayoutWidget_7)
        self.pbMATRIXSPORDERNAME.setObjectName(_fromUtf8("pbMATRIXSPORDERNAME"))
        self.hlMATRIXSPORDERNAME.addWidget(self.pbMATRIXSPORDERNAME)
        self.vlInputFiles.addLayout(self.hlMATRIXSPORDERNAME)
        self.horizontalLayoutWidget = QtGui.QWidget(self.tabInput)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 340, 611, 153))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.vlCosts = QtGui.QVBoxLayout()
        self.vlCosts.setObjectName(_fromUtf8("vlCosts"))
        self.lblNumIter_2 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.lblNumIter_2.setObjectName(_fromUtf8("lblNumIter_2"))
        self.vlCosts.addWidget(self.lblNumIter_2)
        self.spnCOSTTHRESH = QtGui.QDoubleSpinBox(self.horizontalLayoutWidget)
        self.spnCOSTTHRESH.setEnabled(True)
        self.spnCOSTTHRESH.setDecimals(8)
        self.spnCOSTTHRESH.setMinimum(0.0)
        self.spnCOSTTHRESH.setMaximum(1.0)
        self.spnCOSTTHRESH.setSingleStep(1e-06)
        self.spnCOSTTHRESH.setProperty("value", 0.0)
        self.spnCOSTTHRESH.setObjectName(_fromUtf8("spnCOSTTHRESH"))
        self.vlCosts.addWidget(self.spnCOSTTHRESH)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vlCosts.addItem(spacerItem2)
        self.horizontalLayout_2.addLayout(self.vlCosts)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_8 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_3.addWidget(self.label_8)
        self.label_3 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_3.addWidget(self.label_3)
        self.spnTHRESHPEN1 = QtGui.QDoubleSpinBox(self.horizontalLayoutWidget)
        self.spnTHRESHPEN1.setEnabled(True)
        self.spnTHRESHPEN1.setDecimals(8)
        self.spnTHRESHPEN1.setMinimum(0.0)
        self.spnTHRESHPEN1.setMaximum(1.0)
        self.spnTHRESHPEN1.setSingleStep(1e-06)
        self.spnTHRESHPEN1.setProperty("value", 0.14)
        self.spnTHRESHPEN1.setObjectName(_fromUtf8("spnTHRESHPEN1"))
        self.verticalLayout_3.addWidget(self.spnTHRESHPEN1)
        self.label_7 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_3.addWidget(self.label_7)
        self.spnTHRESHPEN2 = QtGui.QDoubleSpinBox(self.horizontalLayoutWidget)
        self.spnTHRESHPEN2.setEnabled(True)
        self.spnTHRESHPEN2.setDecimals(8)
        self.spnTHRESHPEN2.setMinimum(0.0)
        self.spnTHRESHPEN2.setMaximum(1.0)
        self.spnTHRESHPEN2.setSingleStep(1e-06)
        self.spnTHRESHPEN2.setProperty("value", 0.0)
        self.spnTHRESHPEN2.setObjectName(_fromUtf8("spnTHRESHPEN2"))
        self.verticalLayout_3.addWidget(self.spnTHRESHPEN2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.tabWidget.addTab(self.tabInput, _fromUtf8(""))
        self.tabOutput = QtGui.QWidget()
        self.tabOutput.setObjectName(_fromUtf8("tabOutput"))
        self.verticalLayoutWidget_8 = QtGui.QWidget(self.tabOutput)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(10, 10, 611, 481))
        self.verticalLayoutWidget_8.setObjectName(_fromUtf8("verticalLayoutWidget_8"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.verticalLayoutWidget_8)
        self.verticalLayout_7.setSpacing(4)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.lblSCENNAME = QtGui.QLabel(self.verticalLayoutWidget_8)
        self.lblSCENNAME.setObjectName(_fromUtf8("lblSCENNAME"))
        self.verticalLayout_2.addWidget(self.lblSCENNAME)
        self.leSCENNAME = QtGui.QLineEdit(self.verticalLayoutWidget_8)
        self.leSCENNAME.setObjectName(_fromUtf8("leSCENNAME"))
        self.verticalLayout_2.addWidget(self.leSCENNAME)
        self.lblSAVESCEN = QtGui.QLabel(self.verticalLayoutWidget_8)
        self.lblSAVESCEN.setObjectName(_fromUtf8("lblSAVESCEN"))
        self.verticalLayout_2.addWidget(self.lblSAVESCEN)
        self.cbxSAVESCEN = QtGui.QComboBox(self.verticalLayoutWidget_8)
        self.cbxSAVESCEN.setObjectName(_fromUtf8("cbxSAVESCEN"))
        self.cbxSAVESCEN.addItem(_fromUtf8(""))
        self.cbxSAVESCEN.addItem(_fromUtf8(""))
        self.cbxSAVESCEN.addItem(_fromUtf8(""))
        self.verticalLayout_2.addWidget(self.cbxSAVESCEN)
        self.lblSAVESUM = QtGui.QLabel(self.verticalLayoutWidget_8)
        self.lblSAVESUM.setObjectName(_fromUtf8("lblSAVESUM"))
        self.verticalLayout_2.addWidget(self.lblSAVESUM)
        self.cbxSAVESUM = QtGui.QComboBox(self.verticalLayoutWidget_8)
        self.cbxSAVESUM.setObjectName(_fromUtf8("cbxSAVESUM"))
        self.cbxSAVESUM.addItem(_fromUtf8(""))
        self.cbxSAVESUM.addItem(_fromUtf8(""))
        self.cbxSAVESUM.addItem(_fromUtf8(""))
        self.verticalLayout_2.addWidget(self.cbxSAVESUM)
        self.lblSAVERUN = QtGui.QLabel(self.verticalLayoutWidget_8)
        self.lblSAVERUN.setObjectName(_fromUtf8("lblSAVERUN"))
        self.verticalLayout_2.addWidget(self.lblSAVERUN)
        self.cbxSAVERUN = QtGui.QComboBox(self.verticalLayoutWidget_8)
        self.cbxSAVERUN.setInsertPolicy(QtGui.QComboBox.InsertAtBottom)
        self.cbxSAVERUN.setMinimumContentsLength(1)
        self.cbxSAVERUN.setObjectName(_fromUtf8("cbxSAVERUN"))
        self.cbxSAVERUN.addItem(_fromUtf8(""))
        self.cbxSAVERUN.addItem(_fromUtf8(""))
        self.cbxSAVERUN.addItem(_fromUtf8(""))
        self.verticalLayout_2.addWidget(self.cbxSAVERUN)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_16 = QtGui.QLabel(self.verticalLayoutWidget_8)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.verticalLayout.addWidget(self.label_16)
        self.cbxSAVEBEST = QtGui.QComboBox(self.verticalLayoutWidget_8)
        self.cbxSAVEBEST.setObjectName(_fromUtf8("cbxSAVEBEST"))
        self.cbxSAVEBEST.addItem(_fromUtf8(""))
        self.cbxSAVEBEST.addItem(_fromUtf8(""))
        self.cbxSAVEBEST.addItem(_fromUtf8(""))
        self.verticalLayout.addWidget(self.cbxSAVEBEST)
        self.label_17 = QtGui.QLabel(self.verticalLayoutWidget_8)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.verticalLayout.addWidget(self.label_17)
        self.cbxSAVESUMSOLN = QtGui.QComboBox(self.verticalLayoutWidget_8)
        self.cbxSAVESUMSOLN.setObjectName(_fromUtf8("cbxSAVESUMSOLN"))
        self.cbxSAVESUMSOLN.addItem(_fromUtf8(""))
        self.cbxSAVESUMSOLN.addItem(_fromUtf8(""))
        self.cbxSAVESUMSOLN.addItem(_fromUtf8(""))
        self.verticalLayout.addWidget(self.cbxSAVESUMSOLN)
        self.label_14 = QtGui.QLabel(self.verticalLayoutWidget_8)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.verticalLayout.addWidget(self.label_14)
        self.cbxSAVETARGMET = QtGui.QComboBox(self.verticalLayoutWidget_8)
        self.cbxSAVETARGMET.setObjectName(_fromUtf8("cbxSAVETARGMET"))
        self.cbxSAVETARGMET.addItem(_fromUtf8(""))
        self.cbxSAVETARGMET.addItem(_fromUtf8(""))
        self.cbxSAVETARGMET.addItem(_fromUtf8(""))
        self.verticalLayout.addWidget(self.cbxSAVETARGMET)
        self.lblSAVELOG = QtGui.QLabel(self.verticalLayoutWidget_8)
        self.lblSAVELOG.setObjectName(_fromUtf8("lblSAVELOG"))
        self.verticalLayout.addWidget(self.lblSAVELOG)
        self.cbxSAVELOG = QtGui.QComboBox(self.verticalLayoutWidget_8)
        self.cbxSAVELOG.setObjectName(_fromUtf8("cbxSAVELOG"))
        self.cbxSAVELOG.addItem(_fromUtf8(""))
        self.cbxSAVELOG.addItem(_fromUtf8(""))
        self.verticalLayout.addWidget(self.cbxSAVELOG)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        self.label_19 = QtGui.QLabel(self.verticalLayoutWidget_8)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.verticalLayout_7.addWidget(self.label_19)
        self.spnSAVESNAPSTEPS = QtGui.QSpinBox(self.verticalLayoutWidget_8)
        self.spnSAVESNAPSTEPS.setMaximum(1000000000)
        self.spnSAVESNAPSTEPS.setSingleStep(100)
        self.spnSAVESNAPSTEPS.setObjectName(_fromUtf8("spnSAVESNAPSTEPS"))
        self.verticalLayout_7.addWidget(self.spnSAVESNAPSTEPS)
        self.label_20 = QtGui.QLabel(self.verticalLayoutWidget_8)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.verticalLayout_7.addWidget(self.label_20)
        self.spnSAVESNAPCHANGES = QtGui.QSpinBox(self.verticalLayoutWidget_8)
        self.spnSAVESNAPCHANGES.setMaximum(1000000000)
        self.spnSAVESNAPCHANGES.setSingleStep(100)
        self.spnSAVESNAPCHANGES.setObjectName(_fromUtf8("spnSAVESNAPCHANGES"))
        self.verticalLayout_7.addWidget(self.spnSAVESNAPCHANGES)
        self.label_21 = QtGui.QLabel(self.verticalLayoutWidget_8)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.verticalLayout_7.addWidget(self.label_21)
        self.spnSAVESNAPFREQUENCY = QtGui.QSpinBox(self.verticalLayoutWidget_8)
        self.spnSAVESNAPFREQUENCY.setObjectName(_fromUtf8("spnSAVESNAPFREQUENCY"))
        self.verticalLayout_7.addWidget(self.spnSAVESNAPFREQUENCY)
        self.lblSolnMatrix = QtGui.QLabel(self.verticalLayoutWidget_8)
        self.lblSolnMatrix.setObjectName(_fromUtf8("lblSolnMatrix"))
        self.verticalLayout_7.addWidget(self.lblSolnMatrix)
        self.cbxSAVESOLUTIONSMATRIX = QtGui.QComboBox(self.verticalLayoutWidget_8)
        self.cbxSAVESOLUTIONSMATRIX.setObjectName(_fromUtf8("cbxSAVESOLUTIONSMATRIX"))
        self.cbxSAVESOLUTIONSMATRIX.addItem(_fromUtf8(""))
        self.cbxSAVESOLUTIONSMATRIX.addItem(_fromUtf8(""))
        self.cbxSAVESOLUTIONSMATRIX.addItem(_fromUtf8(""))
        self.cbxSAVESOLUTIONSMATRIX.addItem(_fromUtf8(""))
        self.verticalLayout_7.addWidget(self.cbxSAVESOLUTIONSMATRIX)
        self.tabWidget.addTab(self.tabOutput, _fromUtf8(""))

        self.retranslateUi(qm_input)
        self.tabWidget.setCurrentIndex(0)
        self.cbxCLUMPTYPE.setCurrentIndex(0)
        self.cbxRUNMODE.setCurrentIndex(2)
        self.cbxHEURTYPE.setCurrentIndex(0)
        self.cbxITIMPTYPE.setCurrentIndex(1)
        self.cbxVERBOSITY.setCurrentIndex(3)
        self.cbxSAVESCEN.setCurrentIndex(2)
        self.cbxSAVESUM.setCurrentIndex(2)
        self.cbxSAVERUN.setCurrentIndex(2)
        self.cbxSAVEBEST.setCurrentIndex(2)
        self.cbxSAVESUMSOLN.setCurrentIndex(2)
        self.cbxSAVETARGMET.setCurrentIndex(2)
        self.cbxSAVELOG.setCurrentIndex(1)
        self.cbxSAVESOLUTIONSMATRIX.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), qm_input.reject)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), qm_input.accept)
        QtCore.QMetaObject.connectSlotsByName(qm_input)

    def retranslateUi(self, qm_input):
        qm_input.setWindowTitle(QtGui.QApplication.translate("qm_input", "Configure Scenario (input.dat)", None, QtGui.QApplication.UnicodeUTF8))
        self.lblOutputDirectory.setText(QtGui.QApplication.translate("qm_input", "Select scenario directory (where input.dat is or needs to be created)", None, QtGui.QApplication.UnicodeUTF8))
        self.pbScenarioDirectory.setText(QtGui.QApplication.translate("qm_input", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.lblVERSION.setText(QtGui.QApplication.translate("qm_input", "VERSION: input.dat format version", None, QtGui.QApplication.UnicodeUTF8))
        self.leVERSION.setText(QtGui.QApplication.translate("qm_input", "0.1", None, QtGui.QApplication.UnicodeUTF8))
        self.lblBLM.setText(QtGui.QApplication.translate("qm_input", "BLM: Boundary Layer Modifier", None, QtGui.QApplication.UnicodeUTF8))
        self.lblMISSLEVEL.setText(QtGui.QApplication.translate("qm_input", "MISSLEVEL: Threshold for species (feature) targets to marked \"met\"", None, QtGui.QApplication.UnicodeUTF8))
        self.lblPROP.setText(QtGui.QApplication.translate("qm_input", "PROP: proportion of planning units randomly selected as \"in\" to start run", None, QtGui.QApplication.UnicodeUTF8))
        self.lblNUMREPS.setText(QtGui.QApplication.translate("qm_input", "NUMREPS: Number of times this scenario will be run", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCLUMPTYPE.setText(QtGui.QApplication.translate("qm_input", "CLUMPTYPE: Clumping Penalty Type", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxCLUMPTYPE.setItemText(0, QtGui.QApplication.translate("qm_input", "Partial clumps don\'t count", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxCLUMPTYPE.setItemText(1, QtGui.QApplication.translate("qm_input", "Partial clumps count for half", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxCLUMPTYPE.setItemText(2, QtGui.QApplication.translate("qm_input", "Graduated penalty", None, QtGui.QApplication.UnicodeUTF8))
        self.lblRANDSEED.setText(QtGui.QApplication.translate("qm_input", "RANDSEED: Seed for random number generation (-1 to use clock)", None, QtGui.QApplication.UnicodeUTF8))
        self.lblBESTSCORE.setText(QtGui.QApplication.translate("qm_input", "BESTSCORE: for compatibility, see manual for details", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabGeneral), QtGui.QApplication.translate("qm_input", "General", None, QtGui.QApplication.UnicodeUTF8))
        self.lblNUMITNS.setText(QtGui.QApplication.translate("qm_input", "NUMITNS: Number of simulated annealing interations in each run", None, QtGui.QApplication.UnicodeUTF8))
        self.lblNUMTEMP.setText(QtGui.QApplication.translate("qm_input", "NUMTEMP: Number of temperature decreases", None, QtGui.QApplication.UnicodeUTF8))
        self.lblRUNMODE.setText(QtGui.QApplication.translate("qm_input", "RUNMODE: Run mode", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxRUNMODE.setItemText(0, QtGui.QApplication.translate("qm_input", "Use no methods", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxRUNMODE.setItemText(1, QtGui.QApplication.translate("qm_input", "Annealing, heuristic", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxRUNMODE.setItemText(2, QtGui.QApplication.translate("qm_input", "Annealing, iterative improvement", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxRUNMODE.setItemText(3, QtGui.QApplication.translate("qm_input", "Annealing, heuristic, iterative imp.", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxRUNMODE.setItemText(4, QtGui.QApplication.translate("qm_input", "Only heuristic", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxRUNMODE.setItemText(5, QtGui.QApplication.translate("qm_input", "Only interative improvement", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxRUNMODE.setItemText(6, QtGui.QApplication.translate("qm_input", "Heuristic and iterative improvement", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxRUNMODE.setItemText(7, QtGui.QApplication.translate("qm_input", "Annealing only", None, QtGui.QApplication.UnicodeUTF8))
        self.lblHEURTYPE.setText(QtGui.QApplication.translate("qm_input", "HEURTYPE: Heuristic type", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxHEURTYPE.setItemText(0, QtGui.QApplication.translate("qm_input", "Richness", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxHEURTYPE.setItemText(1, QtGui.QApplication.translate("qm_input", "Greedy", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxHEURTYPE.setItemText(2, QtGui.QApplication.translate("qm_input", "Max Rarity", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxHEURTYPE.setItemText(3, QtGui.QApplication.translate("qm_input", "Best Rarity", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxHEURTYPE.setItemText(4, QtGui.QApplication.translate("qm_input", "Mean Rarity", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxHEURTYPE.setItemText(5, QtGui.QApplication.translate("qm_input", "Sum Rarity", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxHEURTYPE.setItemText(6, QtGui.QApplication.translate("qm_input", "Product Irreplaceability", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxHEURTYPE.setItemText(7, QtGui.QApplication.translate("qm_input", "Summation Irreplaceability", None, QtGui.QApplication.UnicodeUTF8))
        self.lblITIMPTYPE.setText(QtGui.QApplication.translate("qm_input", "ITIMPTYPE: Iterative improvement type", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxITIMPTYPE.setItemText(0, QtGui.QApplication.translate("qm_input", "Normal", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxITIMPTYPE.setItemText(1, QtGui.QApplication.translate("qm_input", "Two Step", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxITIMPTYPE.setItemText(2, QtGui.QApplication.translate("qm_input", "Swap", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxITIMPTYPE.setItemText(3, QtGui.QApplication.translate("qm_input", "Normal, Two Step", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSTARTTEMP.setText(QtGui.QApplication.translate("qm_input", "STARTTEMP: Starting temperature (-1 for adaptive annealing)", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCOOLFAC.setText(QtGui.QApplication.translate("qm_input", "COOLFAC: Cooling factor for annealing", None, QtGui.QApplication.UnicodeUTF8))
        self.lblVERBOSITY.setText(QtGui.QApplication.translate("qm_input", "VERBOSITY: Set output verbosity", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxVERBOSITY.setItemText(0, QtGui.QApplication.translate("qm_input", "Silent", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxVERBOSITY.setItemText(1, QtGui.QApplication.translate("qm_input", "Minimal", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxVERBOSITY.setItemText(2, QtGui.QApplication.translate("qm_input", "Intermediate", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxVERBOSITY.setItemText(3, QtGui.QApplication.translate("qm_input", "Verbose", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabRun), QtGui.QApplication.translate("qm_input", "Run and Annealing", None, QtGui.QApplication.UnicodeUTF8))
        self.lbINPUTDIR.setText(QtGui.QApplication.translate("qm_input", "INPUTDIR: Input directory (input)", None, QtGui.QApplication.UnicodeUTF8))
        self.pbINPUTDIR.setText(QtGui.QApplication.translate("qm_input", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.lblOUTPUTDIR.setText(QtGui.QApplication.translate("qm_input", "OUTPUTDIR: Output directory (output)", None, QtGui.QApplication.UnicodeUTF8))
        self.pbOUTPUTDIR.setText(QtGui.QApplication.translate("qm_input", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSPECNAME.setText(QtGui.QApplication.translate("qm_input", "SPECNAME: Species File (spec.dat)", None, QtGui.QApplication.UnicodeUTF8))
        self.pbSPECNAME.setText(QtGui.QApplication.translate("qm_input", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.lblPUNAME.setText(QtGui.QApplication.translate("qm_input", "PUNAME: Planning Unit File (pu.dat)", None, QtGui.QApplication.UnicodeUTF8))
        self.pbPUNAME.setText(QtGui.QApplication.translate("qm_input", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.lblBOUNDNAME.setText(QtGui.QApplication.translate("qm_input", "BOUNDNAME: Boundary File\n"
"(bound.dat)", None, QtGui.QApplication.UnicodeUTF8))
        self.pbBOUNDNAME.setText(QtGui.QApplication.translate("qm_input", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.lblPUVSPRNAME.setText(QtGui.QApplication.translate("qm_input", "PUVSPRNAME: Planning Units vs Species\n"
"(puvspr.dat)", None, QtGui.QApplication.UnicodeUTF8))
        self.pbPUVSPRNAME.setText(QtGui.QApplication.translate("qm_input", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.lblBLOCKDEFNAME.setText(QtGui.QApplication.translate("qm_input", "BLOCKDEFNAME: Block definition file\n"
"(gspec.dat)", None, QtGui.QApplication.UnicodeUTF8))
        self.pbBLOCKDEFNAME.setText(QtGui.QApplication.translate("qm_input", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.lblMATRIXSPORDERNAME.setText(QtGui.QApplication.translate("qm_input", "MATRIXSPORDERNAME: puvspr in species order (puvspr_sporder.dat)", None, QtGui.QApplication.UnicodeUTF8))
        self.pbMATRIXSPORDERNAME.setText(QtGui.QApplication.translate("qm_input", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.lblNumIter_2.setText(QtGui.QApplication.translate("qm_input", "COSTTHRESH: Cost threshold", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("qm_input", "Penalty Factor = A * exp(B) - A ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("qm_input", "THRESHPEN1: Threshold Penalty A", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("qm_input", "THRESHPEN2: Threshold Penalty B", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabInput), QtGui.QApplication.translate("qm_input", "Files and Costs", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSCENNAME.setText(QtGui.QApplication.translate("qm_input", "SCENNAME: Scenario name", None, QtGui.QApplication.UnicodeUTF8))
        self.leSCENNAME.setText(QtGui.QApplication.translate("qm_input", "output", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSAVESCEN.setText(QtGui.QApplication.translate("qm_input", "SAVESCEN: Save scenario info", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxSAVESCEN.setItemText(0, QtGui.QApplication.translate("qm_input", "No", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxSAVESCEN.setItemText(1, QtGui.QApplication.translate("qm_input", ".dat file", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxSAVESCEN.setItemText(2, QtGui.QApplication.translate("qm_input", "CSV with header", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSAVESUM.setText(QtGui.QApplication.translate("qm_input", "SAVESUM: Save summary info", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxSAVESUM.setItemText(0, QtGui.QApplication.translate("qm_input", "No", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxSAVESUM.setItemText(1, QtGui.QApplication.translate("qm_input", ".dat file", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxSAVESUM.setItemText(2, QtGui.QApplication.translate("qm_input", "CSV with header", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSAVERUN.setText(QtGui.QApplication.translate("qm_input", "SAVERUN: Save each run?", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxSAVERUN.setItemText(0, QtGui.QApplication.translate("qm_input", "No", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxSAVERUN.setItemText(1, QtGui.QApplication.translate("qm_input", ".dat file", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxSAVERUN.setItemText(2, QtGui.QApplication.translate("qm_input", "CSV with header", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("qm_input", "SAVEBEST: Save best run?", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxSAVEBEST.setItemText(0, QtGui.QApplication.translate("qm_input", "No", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxSAVEBEST.setItemText(1, QtGui.QApplication.translate("qm_input", ".dat file", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxSAVEBEST.setItemText(2, QtGui.QApplication.translate("qm_input", "CSV with header", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("qm_input", "SAVESUMSOLN: Save frequency info", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxSAVESUMSOLN.setItemText(0, QtGui.QApplication.translate("qm_input", "No", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxSAVESUMSOLN.setItemText(1, QtGui.QApplication.translate("qm_input", ".dat file", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxSAVESUMSOLN.setItemText(2, QtGui.QApplication.translate("qm_input", "CSV with header", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("qm_input", "SAVETARGMET: Save targets met info", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxSAVETARGMET.setItemText(0, QtGui.QApplication.translate("qm_input", "No", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxSAVETARGMET.setItemText(1, QtGui.QApplication.translate("qm_input", ".dat file", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxSAVETARGMET.setItemText(2, QtGui.QApplication.translate("qm_input", "CSV with header", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSAVELOG.setText(QtGui.QApplication.translate("qm_input", "SAVELOG: Save log file?", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxSAVELOG.setItemText(0, QtGui.QApplication.translate("qm_input", "No", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxSAVELOG.setItemText(1, QtGui.QApplication.translate("qm_input", "Yes", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("qm_input", "SAVESNAPSTEPS: Save snapshots each n steps", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("qm_input", "SAVESNAPCHANGES: Save snapshot each n changes", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("qm_input", "SAVESNAPFREQUENCY: Frequency of snapshots", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSolnMatrix.setText(QtGui.QApplication.translate("qm_input", "SAVESOLUTIONSMATRIX: Create output_solutionsmatrix.csv", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxSAVESOLUTIONSMATRIX.setItemText(0, QtGui.QApplication.translate("qm_input", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxSAVESOLUTIONSMATRIX.setItemText(1, QtGui.QApplication.translate("qm_input", "As tab delimited file (.dat)", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxSAVESOLUTIONSMATRIX.setItemText(2, QtGui.QApplication.translate("qm_input", "As comma delimited file (.txt)", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxSAVESOLUTIONSMATRIX.setItemText(3, QtGui.QApplication.translate("qm_input", "As comma delimited file (.csv)", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabOutput), QtGui.QApplication.translate("qm_input", "Marxan Output", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
