# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_qm_calc.ui'
#
# Created: Mon Dec 30 23:11:26 2013
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_qm_calc(object):
    def setupUi(self, qm_calc):
        qm_calc.setObjectName(_fromUtf8("qm_calc"))
        qm_calc.resize(808, 714)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/qm_calc.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        qm_calc.setWindowIcon(icon)
        self.line_3 = QtGui.QFrame(qm_calc)
        self.line_3.setGeometry(QtCore.QRect(0, 320, 801, 21))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.frCalcEdit = QtGui.QFrame(qm_calc)
        self.frCalcEdit.setEnabled(True)
        self.frCalcEdit.setGeometry(QtCore.QRect(0, 10, 801, 310))
        self.frCalcEdit.setFrameShape(QtGui.QFrame.NoFrame)
        self.frCalcEdit.setFrameShadow(QtGui.QFrame.Plain)
        self.frCalcEdit.setObjectName(_fromUtf8("frCalcEdit"))
        self.line_6 = QtGui.QFrame(self.frCalcEdit)
        self.line_6.setGeometry(QtCore.QRect(10, 90, 281, 21))
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.verticalLayoutWidget = QtGui.QWidget(self.frCalcEdit)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 110, 281, 61))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.vlMeasureType = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.vlMeasureType.setMargin(0)
        self.vlMeasureType.setObjectName(_fromUtf8("vlMeasureType"))
        self.lblCalcType = QtGui.QLabel(self.verticalLayoutWidget)
        self.lblCalcType.setObjectName(_fromUtf8("lblCalcType"))
        self.vlMeasureType.addWidget(self.lblCalcType)
        self.hlMeasureType = QtGui.QHBoxLayout()
        self.hlMeasureType.setObjectName(_fromUtf8("hlMeasureType"))
        self.rdoPoints = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.rdoPoints.setChecked(True)
        self.rdoPoints.setObjectName(_fromUtf8("rdoPoints"))
        self.hlMeasureType.addWidget(self.rdoPoints)
        self.rdoLines = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.rdoLines.setObjectName(_fromUtf8("rdoLines"))
        self.hlMeasureType.addWidget(self.rdoLines)
        self.rdoAreas = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.rdoAreas.setObjectName(_fromUtf8("rdoAreas"))
        self.hlMeasureType.addWidget(self.rdoAreas)
        self.rdoRaster = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.rdoRaster.setObjectName(_fromUtf8("rdoRaster"))
        self.hlMeasureType.addWidget(self.rdoRaster)
        self.vlMeasureType.addLayout(self.hlMeasureType)
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.frCalcEdit)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 180, 281, 123))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.vlMeasureLayer = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.vlMeasureLayer.setMargin(0)
        self.vlMeasureLayer.setObjectName(_fromUtf8("vlMeasureLayer"))
        self.lblLayer = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.lblLayer.setObjectName(_fromUtf8("lblLayer"))
        self.vlMeasureLayer.addWidget(self.lblLayer)
        self.cbxMeasureLayer = QtGui.QComboBox(self.verticalLayoutWidget_2)
        self.cbxMeasureLayer.setObjectName(_fromUtf8("cbxMeasureLayer"))
        self.vlMeasureLayer.addWidget(self.cbxMeasureLayer)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.lblSingleMultiple = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.lblSingleMultiple.setObjectName(_fromUtf8("lblSingleMultiple"))
        self.verticalLayout_2.addWidget(self.lblSingleMultiple)
        self.hlCalculation_3 = QtGui.QHBoxLayout()
        self.hlCalculation_3.setObjectName(_fromUtf8("hlCalculation_3"))
        self.rdoCalcSingle = QtGui.QRadioButton(self.verticalLayoutWidget_2)
        self.rdoCalcSingle.setChecked(True)
        self.rdoCalcSingle.setObjectName(_fromUtf8("rdoCalcSingle"))
        self.hlCalculation_3.addWidget(self.rdoCalcSingle)
        self.rdoCalcMulti = QtGui.QRadioButton(self.verticalLayoutWidget_2)
        self.rdoCalcMulti.setChecked(False)
        self.rdoCalcMulti.setObjectName(_fromUtf8("rdoCalcMulti"))
        self.hlCalculation_3.addWidget(self.rdoCalcMulti)
        self.verticalLayout_2.addLayout(self.hlCalculation_3)
        self.vlMeasureLayer.addLayout(self.verticalLayout_2)
        self.line = QtGui.QFrame(self.frCalcEdit)
        self.line.setGeometry(QtCore.QRect(293, 10, 16, 301))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.layoutWidget_3 = QtGui.QWidget(self.frCalcEdit)
        self.layoutWidget_3.setGeometry(QtCore.QRect(310, 10, 481, 131))
        self.layoutWidget_3.setObjectName(_fromUtf8("layoutWidget_3"))
        self.vlCalc = QtGui.QVBoxLayout(self.layoutWidget_3)
        self.vlCalc.setMargin(0)
        self.vlCalc.setObjectName(_fromUtf8("vlCalc"))
        self.lblMeasureOrCalc = QtGui.QLabel(self.layoutWidget_3)
        self.lblMeasureOrCalc.setObjectName(_fromUtf8("lblMeasureOrCalc"))
        self.vlCalc.addWidget(self.lblMeasureOrCalc)
        self.hlCalculation = QtGui.QHBoxLayout()
        self.hlCalculation.setObjectName(_fromUtf8("hlCalculation"))
        self.rdoMeasure = QtGui.QRadioButton(self.layoutWidget_3)
        self.rdoMeasure.setChecked(True)
        self.rdoMeasure.setObjectName(_fromUtf8("rdoMeasure"))
        self.hlCalculation.addWidget(self.rdoMeasure)
        self.rdoCalculate = QtGui.QRadioButton(self.layoutWidget_3)
        self.rdoCalculate.setObjectName(_fromUtf8("rdoCalculate"))
        self.hlCalculation.addWidget(self.rdoCalculate)
        self.rdoPresence = QtGui.QRadioButton(self.layoutWidget_3)
        self.rdoPresence.setChecked(False)
        self.rdoPresence.setObjectName(_fromUtf8("rdoPresence"))
        self.hlCalculation.addWidget(self.rdoPresence)
        self.vlCalc.addLayout(self.hlCalculation)
        self.lblCalcField = QtGui.QLabel(self.layoutWidget_3)
        self.lblCalcField.setEnabled(False)
        self.lblCalcField.setObjectName(_fromUtf8("lblCalcField"))
        self.vlCalc.addWidget(self.lblCalcField)
        self.cbxCalcField = QtGui.QComboBox(self.layoutWidget_3)
        self.cbxCalcField.setEnabled(False)
        self.cbxCalcField.setObjectName(_fromUtf8("cbxCalcField"))
        self.vlCalc.addWidget(self.cbxCalcField)
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.frCalcEdit)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(310, 140, 481, 57))
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.lblMultipleAction = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.lblMultipleAction.setObjectName(_fromUtf8("lblMultipleAction"))
        self.verticalLayout.addWidget(self.lblMultipleAction)
        self.hlCalculation_2 = QtGui.QHBoxLayout()
        self.hlCalculation_2.setObjectName(_fromUtf8("hlCalculation_2"))
        self.rdoSum = QtGui.QRadioButton(self.verticalLayoutWidget_3)
        self.rdoSum.setChecked(True)
        self.rdoSum.setObjectName(_fromUtf8("rdoSum"))
        self.hlCalculation_2.addWidget(self.rdoSum)
        self.rdoMean = QtGui.QRadioButton(self.verticalLayoutWidget_3)
        self.rdoMean.setChecked(False)
        self.rdoMean.setObjectName(_fromUtf8("rdoMean"))
        self.hlCalculation_2.addWidget(self.rdoMean)
        self.rdoMax = QtGui.QRadioButton(self.verticalLayoutWidget_3)
        self.rdoMax.setObjectName(_fromUtf8("rdoMax"))
        self.hlCalculation_2.addWidget(self.rdoMax)
        self.rdoMin = QtGui.QRadioButton(self.verticalLayoutWidget_3)
        self.rdoMin.setObjectName(_fromUtf8("rdoMin"))
        self.hlCalculation_2.addWidget(self.rdoMin)
        self.rdoCount = QtGui.QRadioButton(self.verticalLayoutWidget_3)
        self.rdoCount.setObjectName(_fromUtf8("rdoCount"))
        self.hlCalculation_2.addWidget(self.rdoCount)
        self.verticalLayout.addLayout(self.hlCalculation_2)
        self.line_5 = QtGui.QFrame(self.frCalcEdit)
        self.line_5.setGeometry(QtCore.QRect(310, 200, 481, 21))
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.frCalcEdit)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(310, 220, 488, 89))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.vlOutput = QtGui.QVBoxLayout()
        self.vlOutput.setObjectName(_fromUtf8("vlOutput"))
        self.lblSelectField = QtGui.QLabel(self.horizontalLayoutWidget)
        self.lblSelectField.setObjectName(_fromUtf8("lblSelectField"))
        self.vlOutput.addWidget(self.lblSelectField)
        self.cbxSelectField = QtGui.QComboBox(self.horizontalLayoutWidget)
        self.cbxSelectField.setObjectName(_fromUtf8("cbxSelectField"))
        self.vlOutput.addWidget(self.cbxSelectField)
        self.horizontalLayout.addLayout(self.vlOutput)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.lblNewField = QtGui.QLabel(self.horizontalLayoutWidget)
        self.lblNewField.setEnabled(True)
        self.lblNewField.setObjectName(_fromUtf8("lblNewField"))
        self.verticalLayout_3.addWidget(self.lblNewField)
        self.leNewField = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.leNewField.setEnabled(True)
        self.leNewField.setMaxLength(10)
        self.leNewField.setReadOnly(False)
        self.leNewField.setObjectName(_fromUtf8("leNewField"))
        self.verticalLayout_3.addWidget(self.leNewField)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.layoutWidget = QtGui.QWidget(self.frCalcEdit)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 281, 81))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.vlPlanningGrid = QtGui.QVBoxLayout(self.layoutWidget)
        self.vlPlanningGrid.setMargin(0)
        self.vlPlanningGrid.setObjectName(_fromUtf8("vlPlanningGrid"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lblPlanningGrid = QtGui.QLabel(self.layoutWidget)
        self.lblPlanningGrid.setObjectName(_fromUtf8("lblPlanningGrid"))
        self.horizontalLayout_2.addWidget(self.lblPlanningGrid)
        self.lblPuId = QtGui.QLabel(self.layoutWidget)
        self.lblPuId.setObjectName(_fromUtf8("lblPuId"))
        self.horizontalLayout_2.addWidget(self.lblPuId)
        self.vlPlanningGrid.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.cbxPlanningGrid = QtGui.QComboBox(self.layoutWidget)
        self.cbxPlanningGrid.setObjectName(_fromUtf8("cbxPlanningGrid"))
        self.horizontalLayout_3.addWidget(self.cbxPlanningGrid)
        self.cbxPuId = QtGui.QComboBox(self.layoutWidget)
        self.cbxPuId.setObjectName(_fromUtf8("cbxPuId"))
        self.horizontalLayout_3.addWidget(self.cbxPuId)
        self.vlPlanningGrid.addLayout(self.horizontalLayout_3)
        self.twCalculations = QtGui.QTableWidget(qm_calc)
        self.twCalculations.setGeometry(QtCore.QRect(10, 380, 791, 241))
        self.twCalculations.setEditTriggers(QtGui.QAbstractItemView.SelectedClicked)
        self.twCalculations.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.twCalculations.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.twCalculations.setObjectName(_fromUtf8("twCalculations"))
        self.twCalculations.setColumnCount(0)
        self.twCalculations.setRowCount(0)
        self.layoutWidget1 = QtGui.QWidget(qm_calc)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 340, 411, 33))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.pbNew = QtGui.QPushButton(self.layoutWidget1)
        self.pbNew.setEnabled(False)
        self.pbNew.setObjectName(_fromUtf8("pbNew"))
        self.horizontalLayout_4.addWidget(self.pbNew)
        self.pbSave = QtGui.QPushButton(self.layoutWidget1)
        self.pbSave.setEnabled(False)
        self.pbSave.setObjectName(_fromUtf8("pbSave"))
        self.horizontalLayout_4.addWidget(self.pbSave)
        self.pbCancel = QtGui.QPushButton(self.layoutWidget1)
        self.pbCancel.setEnabled(False)
        self.pbCancel.setObjectName(_fromUtf8("pbCancel"))
        self.horizontalLayout_4.addWidget(self.pbCancel)
        self.pbDelete = QtGui.QPushButton(self.layoutWidget1)
        self.pbDelete.setEnabled(False)
        self.pbDelete.setObjectName(_fromUtf8("pbDelete"))
        self.horizontalLayout_4.addWidget(self.pbDelete)
        self.frProcessManagement = QtGui.QFrame(qm_calc)
        self.frProcessManagement.setGeometry(QtCore.QRect(0, 620, 801, 80))
        self.frProcessManagement.setFrameShape(QtGui.QFrame.NoFrame)
        self.frProcessManagement.setFrameShadow(QtGui.QFrame.Plain)
        self.frProcessManagement.setObjectName(_fromUtf8("frProcessManagement"))
        self.line_4 = QtGui.QFrame(self.frProcessManagement)
        self.line_4.setGeometry(QtCore.QRect(10, -10, 791, 30))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.verticalLayoutWidget_4 = QtGui.QWidget(self.frProcessManagement)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(430, 10, 368, 61))
        self.verticalLayoutWidget_4.setObjectName(_fromUtf8("verticalLayoutWidget_4"))
        self.vlProcessManagement = QtGui.QVBoxLayout(self.verticalLayoutWidget_4)
        self.vlProcessManagement.setSpacing(0)
        self.vlProcessManagement.setMargin(0)
        self.vlProcessManagement.setObjectName(_fromUtf8("vlProcessManagement"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label = QtGui.QLabel(self.verticalLayoutWidget_4)
        self.label.setText(_fromUtf8(""))
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_6.addWidget(self.label)
        self.vlProcessManagement.addLayout(self.verticalLayout_6)
        self.hlActions = QtGui.QHBoxLayout()
        self.hlActions.setSpacing(8)
        self.hlActions.setObjectName(_fromUtf8("hlActions"))
        self.pbOpenList = QtGui.QPushButton(self.verticalLayoutWidget_4)
        self.pbOpenList.setObjectName(_fromUtf8("pbOpenList"))
        self.hlActions.addWidget(self.pbOpenList)
        self.pbSaveList = QtGui.QPushButton(self.verticalLayoutWidget_4)
        self.pbSaveList.setObjectName(_fromUtf8("pbSaveList"))
        self.hlActions.addWidget(self.pbSaveList)
        self.pbClose = QtGui.QPushButton(self.verticalLayoutWidget_4)
        self.pbClose.setObjectName(_fromUtf8("pbClose"))
        self.hlActions.addWidget(self.pbClose)
        self.pbRun = QtGui.QPushButton(self.verticalLayoutWidget_4)
        self.pbRun.setEnabled(False)
        self.pbRun.setObjectName(_fromUtf8("pbRun"))
        self.hlActions.addWidget(self.pbRun)
        self.vlProcessManagement.addLayout(self.hlActions)
        self.verticalLayoutWidget_5 = QtGui.QWidget(self.frProcessManagement)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(10, 10, 151, 61))
        self.verticalLayoutWidget_5.setObjectName(_fromUtf8("verticalLayoutWidget_5"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.lblProcess = QtGui.QLabel(self.verticalLayoutWidget_5)
        self.lblProcess.setObjectName(_fromUtf8("lblProcess"))
        self.verticalLayout_4.addWidget(self.lblProcess)
        self.pbListProgress = QtGui.QProgressBar(self.verticalLayoutWidget_5)
        self.pbListProgress.setProperty("value", 0)
        self.pbListProgress.setAlignment(QtCore.Qt.AlignCenter)
        self.pbListProgress.setTextVisible(True)
        self.pbListProgress.setObjectName(_fromUtf8("pbListProgress"))
        self.verticalLayout_4.addWidget(self.pbListProgress)
        self.verticalLayoutWidget_6 = QtGui.QWidget(self.frProcessManagement)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(170, 10, 251, 61))
        self.verticalLayoutWidget_6.setObjectName(_fromUtf8("verticalLayoutWidget_6"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.lblCalculation = QtGui.QLabel(self.verticalLayoutWidget_6)
        self.lblCalculation.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lblCalculation.setObjectName(_fromUtf8("lblCalculation"))
        self.horizontalLayout_5.addWidget(self.lblCalculation)
        self.lblCPAction = QtGui.QLabel(self.verticalLayoutWidget_6)
        self.lblCPAction.setText(_fromUtf8(""))
        self.lblCPAction.setObjectName(_fromUtf8("lblCPAction"))
        self.horizontalLayout_5.addWidget(self.lblCPAction)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.pbCalculationProgress = QtGui.QProgressBar(self.verticalLayoutWidget_6)
        self.pbCalculationProgress.setProperty("value", 0)
        self.pbCalculationProgress.setObjectName(_fromUtf8("pbCalculationProgress"))
        self.verticalLayout_5.addWidget(self.pbCalculationProgress)
        self.horizontalLayoutWidget_2 = QtGui.QWidget(qm_calc)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(440, 340, 361, 31))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.lblWriteLabel = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.lblWriteLabel.setEnabled(True)
        self.lblWriteLabel.setObjectName(_fromUtf8("lblWriteLabel"))
        self.horizontalLayout_6.addWidget(self.lblWriteLabel)
        self.rdoWLyr = QtGui.QRadioButton(self.horizontalLayoutWidget_2)
        self.rdoWLyr.setChecked(True)
        self.rdoWLyr.setObjectName(_fromUtf8("rdoWLyr"))
        self.horizontalLayout_6.addWidget(self.rdoWLyr)
        self.rdoWTF = QtGui.QRadioButton(self.horizontalLayoutWidget_2)
        self.rdoWTF.setObjectName(_fromUtf8("rdoWTF"))
        self.horizontalLayout_6.addWidget(self.rdoWTF)

        self.retranslateUi(qm_calc)
        QtCore.QMetaObject.connectSlotsByName(qm_calc)

    def retranslateUi(self, qm_calc):
        qm_calc.setWindowTitle(QtGui.QApplication.translate("qm_calc", "Calculate Planning Grid Values", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCalcType.setText(QtGui.QApplication.translate("qm_calc", "Select input layer type", None, QtGui.QApplication.UnicodeUTF8))
        self.rdoPoints.setText(QtGui.QApplication.translate("qm_calc", "Point", None, QtGui.QApplication.UnicodeUTF8))
        self.rdoLines.setText(QtGui.QApplication.translate("qm_calc", "Line", None, QtGui.QApplication.UnicodeUTF8))
        self.rdoAreas.setText(QtGui.QApplication.translate("qm_calc", "Area", None, QtGui.QApplication.UnicodeUTF8))
        self.rdoRaster.setText(QtGui.QApplication.translate("qm_calc", "Raster", None, QtGui.QApplication.UnicodeUTF8))
        self.lblLayer.setText(QtGui.QApplication.translate("qm_calc", "Select layer to measure", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSingleMultiple.setText(QtGui.QApplication.translate("qm_calc", "On intersection assign value to", None, QtGui.QApplication.UnicodeUTF8))
        self.rdoCalcSingle.setText(QtGui.QApplication.translate("qm_calc", "Single Field", None, QtGui.QApplication.UnicodeUTF8))
        self.rdoCalcMulti.setText(QtGui.QApplication.translate("qm_calc", "Multiple Fields", None, QtGui.QApplication.UnicodeUTF8))
        self.lblMeasureOrCalc.setText(QtGui.QApplication.translate("qm_calc", "On intersection use the following value", None, QtGui.QApplication.UnicodeUTF8))
        self.rdoMeasure.setText(QtGui.QApplication.translate("qm_calc", "Measure (count,length,area)", None, QtGui.QApplication.UnicodeUTF8))
        self.rdoCalculate.setText(QtGui.QApplication.translate("qm_calc", "Measure x Field", None, QtGui.QApplication.UnicodeUTF8))
        self.rdoPresence.setText(QtGui.QApplication.translate("qm_calc", "Presence", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCalcField.setText(QtGui.QApplication.translate("qm_calc", "Select Field for Calculation", None, QtGui.QApplication.UnicodeUTF8))
        self.lblMultipleAction.setText(QtGui.QApplication.translate("qm_calc", "On multiple intersections use", None, QtGui.QApplication.UnicodeUTF8))
        self.rdoSum.setText(QtGui.QApplication.translate("qm_calc", "Sum", None, QtGui.QApplication.UnicodeUTF8))
        self.rdoMean.setText(QtGui.QApplication.translate("qm_calc", "Mean", None, QtGui.QApplication.UnicodeUTF8))
        self.rdoMax.setText(QtGui.QApplication.translate("qm_calc", "Max", None, QtGui.QApplication.UnicodeUTF8))
        self.rdoMin.setText(QtGui.QApplication.translate("qm_calc", "Min", None, QtGui.QApplication.UnicodeUTF8))
        self.rdoCount.setText(QtGui.QApplication.translate("qm_calc", "Count", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSelectField.setText(QtGui.QApplication.translate("qm_calc", "Select Output Field Name", None, QtGui.QApplication.UnicodeUTF8))
        self.lblNewField.setText(QtGui.QApplication.translate("qm_calc", "Enter New Field Name", None, QtGui.QApplication.UnicodeUTF8))
        self.lblPlanningGrid.setText(QtGui.QApplication.translate("qm_calc", "Planning Unit Layer", None, QtGui.QApplication.UnicodeUTF8))
        self.lblPuId.setText(QtGui.QApplication.translate("qm_calc", "Planning Unit Id", None, QtGui.QApplication.UnicodeUTF8))
        self.pbNew.setText(QtGui.QApplication.translate("qm_calc", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.pbSave.setText(QtGui.QApplication.translate("qm_calc", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.pbCancel.setText(QtGui.QApplication.translate("qm_calc", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.pbDelete.setText(QtGui.QApplication.translate("qm_calc", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.pbOpenList.setText(QtGui.QApplication.translate("qm_calc", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.pbSaveList.setText(QtGui.QApplication.translate("qm_calc", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.pbClose.setText(QtGui.QApplication.translate("qm_calc", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.pbRun.setText(QtGui.QApplication.translate("qm_calc", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.lblProcess.setText(QtGui.QApplication.translate("qm_calc", "Calculations List: ", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCalculation.setText(QtGui.QApplication.translate("qm_calc", "Current: ", None, QtGui.QApplication.UnicodeUTF8))
        self.lblWriteLabel.setText(QtGui.QApplication.translate("qm_calc", "Write results to:", None, QtGui.QApplication.UnicodeUTF8))
        self.rdoWLyr.setText(QtGui.QApplication.translate("qm_calc", "PU Layer", None, QtGui.QApplication.UnicodeUTF8))
        self.rdoWTF.setText(QtGui.QApplication.translate("qm_calc", "CSV File(s)", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
