# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_qm_mkgrid.ui'
#
# Created: Fri Sep 20 14:08:42 2013
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_qm_mkgrid(object):
    def setupUi(self, qm_mkgrid):
        qm_mkgrid.setObjectName(_fromUtf8("qm_mkgrid"))
        qm_mkgrid.setWindowModality(QtCore.Qt.NonModal)
        qm_mkgrid.resize(460, 588)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/qm_mkgrid.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        qm_mkgrid.setWindowIcon(icon)
        qm_mkgrid.setSizeGripEnabled(False)
        self.gridLayout_2 = QtGui.QGridLayout(qm_mkgrid)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.groupBox = QtGui.QGroupBox(qm_mkgrid)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.btnUpdate = QtGui.QToolButton(self.groupBox)
        self.btnUpdate.setMinimumSize(QtCore.QSize(0, 30))
        self.btnUpdate.setObjectName(_fromUtf8("btnUpdate"))
        self.gridLayout.addWidget(self.btnUpdate, 1, 0, 1, 1)
        self.inShape = QtGui.QComboBox(self.groupBox)
        self.inShape.setObjectName(_fromUtf8("inShape"))
        self.gridLayout.addWidget(self.inShape, 0, 0, 1, 2)
        self.btnCanvas = QtGui.QToolButton(self.groupBox)
        self.btnCanvas.setMinimumSize(QtCore.QSize(0, 30))
        self.btnCanvas.setObjectName(_fromUtf8("btnCanvas"))
        self.gridLayout.addWidget(self.btnCanvas, 1, 1, 1, 1)
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setObjectName(_fromUtf8("hboxlayout"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setEnabled(True)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.hboxlayout.addWidget(self.label_3)
        self.spnXmax = QtGui.QDoubleSpinBox(self.groupBox)
        self.spnXmax.setMinimum(-1000000000.0)
        self.spnXmax.setMaximum(1000000000.0)
        self.spnXmax.setObjectName(_fromUtf8("spnXmax"))
        self.hboxlayout.addWidget(self.spnXmax)
        self.gridLayout.addLayout(self.hboxlayout, 3, 0, 1, 1)
        self.hboxlayout1 = QtGui.QHBoxLayout()
        self.hboxlayout1.setObjectName(_fromUtf8("hboxlayout1"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setEnabled(True)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.hboxlayout1.addWidget(self.label_4)
        self.spnYmin = QtGui.QDoubleSpinBox(self.groupBox)
        self.spnYmin.setMinimum(-1000000000.0)
        self.spnYmin.setMaximum(1000000000.0)
        self.spnYmin.setObjectName(_fromUtf8("spnYmin"))
        self.hboxlayout1.addWidget(self.spnYmin)
        self.gridLayout.addLayout(self.hboxlayout1, 2, 1, 1, 1)
        self.hboxlayout2 = QtGui.QHBoxLayout()
        self.hboxlayout2.setObjectName(_fromUtf8("hboxlayout2"))
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setEnabled(True)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.hboxlayout2.addWidget(self.label_5)
        self.spnYmax = QtGui.QDoubleSpinBox(self.groupBox)
        self.spnYmax.setMinimum(-1000000000.0)
        self.spnYmax.setMaximum(1000000000.0)
        self.spnYmax.setObjectName(_fromUtf8("spnYmax"))
        self.hboxlayout2.addWidget(self.spnYmax)
        self.gridLayout.addLayout(self.hboxlayout2, 3, 1, 1, 1)
        self.hboxlayout3 = QtGui.QHBoxLayout()
        self.hboxlayout3.setObjectName(_fromUtf8("hboxlayout3"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setEnabled(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.hboxlayout3.addWidget(self.label)
        self.spnXmin = QtGui.QDoubleSpinBox(self.groupBox)
        self.spnXmin.setMinimum(-1000000000.0)
        self.spnXmin.setMaximum(1000000000.0)
        self.spnXmin.setObjectName(_fromUtf8("spnXmin"))
        self.hboxlayout3.addWidget(self.spnXmin)
        self.gridLayout.addLayout(self.hboxlayout3, 2, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 2)
        self.buttonBox_2 = QtGui.QDialogButtonBox(qm_mkgrid)
        self.buttonBox_2.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox_2.setStandardButtons(QtGui.QDialogButtonBox.Close|QtGui.QDialogButtonBox.Ok)
        self.buttonBox_2.setObjectName(_fromUtf8("buttonBox_2"))
        self.gridLayout_2.addWidget(self.buttonBox_2, 12, 1, 1, 1)
        self.progressBar = QtGui.QProgressBar(qm_mkgrid)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.gridLayout_2.addWidget(self.progressBar, 12, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.cbLimit = QtGui.QCheckBox(qm_mkgrid)
        self.cbLimit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cbLimit.setObjectName(_fromUtf8("cbLimit"))
        self.horizontalLayout_2.addWidget(self.cbLimit)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 4, 0, 1, 2)
        self.gridBox = QtGui.QGroupBox(qm_mkgrid)
        self.gridBox.setObjectName(_fromUtf8("gridBox"))
        self.gridlayout = QtGui.QGridLayout(self.gridBox)
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        self.rdoArea = QtGui.QRadioButton(self.gridBox)
        self.rdoArea.setChecked(True)
        self.rdoArea.setObjectName(_fromUtf8("rdoArea"))
        self.gridlayout.addWidget(self.rdoArea, 0, 0, 1, 2)
        self.lblArea = QtGui.QLabel(self.gridBox)
        self.lblArea.setEnabled(True)
        self.lblArea.setObjectName(_fromUtf8("lblArea"))
        self.gridlayout.addWidget(self.lblArea, 3, 0, 1, 2)
        self.lblLength = QtGui.QLabel(self.gridBox)
        self.lblLength.setEnabled(False)
        self.lblLength.setObjectName(_fromUtf8("lblLength"))
        self.gridlayout.addWidget(self.lblLength, 5, 0, 1, 2)
        self.spnUnitArea = QtGui.QDoubleSpinBox(self.gridBox)
        self.spnUnitArea.setEnabled(True)
        self.spnUnitArea.setDecimals(4)
        self.spnUnitArea.setMinimum(0.0001)
        self.spnUnitArea.setMaximum(1000000000.0)
        self.spnUnitArea.setSingleStep(100.0)
        self.spnUnitArea.setProperty("value", 1000.0)
        self.spnUnitArea.setObjectName(_fromUtf8("spnUnitArea"))
        self.gridlayout.addWidget(self.spnUnitArea, 3, 2, 1, 1)
        self.spnSideLength = QtGui.QDoubleSpinBox(self.gridBox)
        self.spnSideLength.setEnabled(False)
        self.spnSideLength.setDecimals(4)
        self.spnSideLength.setMinimum(0.0001)
        self.spnSideLength.setMaximum(1000000000.0)
        self.spnSideLength.setSingleStep(10.0)
        self.spnSideLength.setProperty("value", 100.0)
        self.spnSideLength.setObjectName(_fromUtf8("spnSideLength"))
        self.gridlayout.addWidget(self.spnSideLength, 5, 2, 1, 1)
        self.rdoSideLength = QtGui.QRadioButton(self.gridBox)
        self.rdoSideLength.setChecked(False)
        self.rdoSideLength.setObjectName(_fromUtf8("rdoSideLength"))
        self.gridlayout.addWidget(self.rdoSideLength, 0, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout.addItem(spacerItem1, 3, 4, 1, 1)
        self.gridLayout_2.addWidget(self.gridBox, 5, 0, 1, 2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_7 = QtGui.QLabel(qm_mkgrid)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_4.addWidget(self.label_7)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.gbShape = QtGui.QGroupBox(qm_mkgrid)
        self.gbShape.setTitle(_fromUtf8(""))
        self.gbShape.setObjectName(_fromUtf8("gbShape"))
        self.rdoHexagon = QtGui.QRadioButton(self.gbShape)
        self.rdoHexagon.setGeometry(QtCore.QRect(10, 0, 142, 30))
        self.rdoHexagon.setChecked(True)
        self.rdoHexagon.setObjectName(_fromUtf8("rdoHexagon"))
        self.rdoSquare = QtGui.QRadioButton(self.gbShape)
        self.rdoSquare.setGeometry(QtCore.QRect(220, 0, 216, 30))
        self.rdoSquare.setCheckable(True)
        self.rdoSquare.setChecked(False)
        self.rdoSquare.setObjectName(_fromUtf8("rdoSquare"))
        self.horizontalLayout_5.addWidget(self.gbShape)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_6 = QtGui.QLabel(qm_mkgrid)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout.addWidget(self.label_6)
        self.leUnitNumber = QtGui.QLineEdit(qm_mkgrid)
        self.leUnitNumber.setAcceptDrops(True)
        self.leUnitNumber.setReadOnly(True)
        self.leUnitNumber.setObjectName(_fromUtf8("leUnitNumber"))
        self.horizontalLayout.addWidget(self.leUnitNumber)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_2 = QtGui.QLabel(qm_mkgrid)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.hboxlayout4 = QtGui.QHBoxLayout()
        self.hboxlayout4.setObjectName(_fromUtf8("hboxlayout4"))
        self.outShape = QtGui.QLineEdit(qm_mkgrid)
        self.outShape.setReadOnly(True)
        self.outShape.setObjectName(_fromUtf8("outShape"))
        self.hboxlayout4.addWidget(self.outShape)
        self.toolOut = QtGui.QToolButton(qm_mkgrid)
        self.toolOut.setObjectName(_fromUtf8("toolOut"))
        self.hboxlayout4.addWidget(self.toolOut)
        self.verticalLayout.addLayout(self.hboxlayout4)
        self.gridLayout_2.addLayout(self.verticalLayout, 6, 0, 1, 2)

        self.retranslateUi(qm_mkgrid)
        QtCore.QObject.connect(self.buttonBox_2, QtCore.SIGNAL(_fromUtf8("accepted()")), qm_mkgrid.accept)
        QtCore.QObject.connect(self.buttonBox_2, QtCore.SIGNAL(_fromUtf8("rejected()")), qm_mkgrid.close)
        QtCore.QObject.connect(self.rdoArea, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.lblArea.setEnabled)
        QtCore.QObject.connect(self.rdoArea, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.spnUnitArea.setEnabled)
        QtCore.QObject.connect(self.rdoArea, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.lblLength.setDisabled)
        QtCore.QObject.connect(self.rdoArea, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.spnSideLength.setDisabled)
        QtCore.QObject.connect(self.rdoSideLength, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.lblArea.setDisabled)
        QtCore.QObject.connect(self.rdoSideLength, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.spnUnitArea.setDisabled)
        QtCore.QObject.connect(self.rdoSideLength, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.lblLength.setEnabled)
        QtCore.QObject.connect(self.rdoSideLength, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.spnSideLength.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(qm_mkgrid)

    def retranslateUi(self, qm_mkgrid):
        qm_mkgrid.setWindowTitle(QtGui.QApplication.translate("qm_mkgrid", "Generate Planning Grid", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("qm_mkgrid", "Planning Grid Extent", None, QtGui.QApplication.UnicodeUTF8))
        self.btnUpdate.setText(QtGui.QApplication.translate("qm_mkgrid", "Update extents from layer", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCanvas.setText(QtGui.QApplication.translate("qm_mkgrid", "Update extents from canvas", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("qm_mkgrid", "X Max", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("qm_mkgrid", "Y Min", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("qm_mkgrid", "Y Max", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("qm_mkgrid", "X Min", None, QtGui.QApplication.UnicodeUTF8))
        self.cbLimit.setText(QtGui.QApplication.translate("qm_mkgrid", "Limit creation of grid by intersection with layer", None, QtGui.QApplication.UnicodeUTF8))
        self.gridBox.setTitle(QtGui.QApplication.translate("qm_mkgrid", "Calculate grid in projection units using:", None, QtGui.QApplication.UnicodeUTF8))
        self.rdoArea.setText(QtGui.QApplication.translate("qm_mkgrid", "Unit Area", None, QtGui.QApplication.UnicodeUTF8))
        self.lblArea.setText(QtGui.QApplication.translate("qm_mkgrid", "Unit Area", None, QtGui.QApplication.UnicodeUTF8))
        self.lblLength.setText(QtGui.QApplication.translate("qm_mkgrid", "Side Length", None, QtGui.QApplication.UnicodeUTF8))
        self.rdoSideLength.setText(QtGui.QApplication.translate("qm_mkgrid", "Side Length", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("qm_mkgrid", "<html><head/><body><p><span style=\" font-weight:600;\">Planning Unit Shape</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.rdoHexagon.setText(QtGui.QApplication.translate("qm_mkgrid", "Hexagons", None, QtGui.QApplication.UnicodeUTF8))
        self.rdoSquare.setText(QtGui.QApplication.translate("qm_mkgrid", "Squares", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("qm_mkgrid", "Approximate number of units will be: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("qm_mkgrid", "Output shapefile", None, QtGui.QApplication.UnicodeUTF8))
        self.toolOut.setText(QtGui.QApplication.translate("qm_mkgrid", "Browse", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
