# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_qm_export.ui'
#
# Created: Tue Sep  3 17:11:26 2013
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_qm_export(object):
    def setupUi(self, qm_export):
        qm_export.setObjectName(_fromUtf8("qm_export"))
        qm_export.resize(725, 712)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(qm_export.sizePolicy().hasHeightForWidth())
        qm_export.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/qm_export.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        qm_export.setWindowIcon(icon)
        self.verticalLayoutWidget_2 = QtGui.QWidget(qm_export)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 80, 701, 62))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.vlOutputDir = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.vlOutputDir.setMargin(0)
        self.vlOutputDir.setObjectName(_fromUtf8("vlOutputDir"))
        self.lblOutputDirectory = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.lblOutputDirectory.setObjectName(_fromUtf8("lblOutputDirectory"))
        self.vlOutputDir.addWidget(self.lblOutputDirectory)
        self._2 = QtGui.QHBoxLayout()
        self._2.setObjectName(_fromUtf8("_2"))
        self.outDirectory = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        self.outDirectory.setReadOnly(True)
        self.outDirectory.setObjectName(_fromUtf8("outDirectory"))
        self._2.addWidget(self.outDirectory)
        self.pbOutputDir = QtGui.QToolButton(self.verticalLayoutWidget_2)
        self.pbOutputDir.setObjectName(_fromUtf8("pbOutputDir"))
        self._2.addWidget(self.pbOutputDir)
        self.vlOutputDir.addLayout(self._2)
        self.layoutWidget = QtGui.QWidget(qm_export)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 670, 701, 33))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.hlActions = QtGui.QHBoxLayout(self.layoutWidget)
        self.hlActions.setMargin(0)
        self.hlActions.setObjectName(_fromUtf8("hlActions"))
        self.progressBar = QtGui.QProgressBar(self.layoutWidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.hlActions.addWidget(self.progressBar)
        self.lbExportAction = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbExportAction.sizePolicy().hasHeightForWidth())
        self.lbExportAction.setSizePolicy(sizePolicy)
        self.lbExportAction.setText(_fromUtf8(""))
        self.lbExportAction.setObjectName(_fromUtf8("lbExportAction"))
        self.hlActions.addWidget(self.lbExportAction)
        self.buttonBox = QtGui.QDialogButtonBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.hlActions.addWidget(self.buttonBox)
        self.tabWidget = QtGui.QTabWidget(qm_export)
        self.tabWidget.setGeometry(QtCore.QRect(10, 140, 701, 521))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.layoutWidget1 = QtGui.QWidget(self.tab)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 40, 681, 441))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.vlFieldList = QtGui.QVBoxLayout(self.layoutWidget1)
        self.vlFieldList.setMargin(0)
        self.vlFieldList.setObjectName(_fromUtf8("vlFieldList"))
        self.twFields = QtGui.QTableWidget(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.twFields.sizePolicy().hasHeightForWidth())
        self.twFields.setSizePolicy(sizePolicy)
        self.twFields.setObjectName(_fromUtf8("twFields"))
        self.twFields.setColumnCount(0)
        self.twFields.setRowCount(0)
        self.vlFieldList.addWidget(self.twFields)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pbSelectAll = QtGui.QPushButton(self.layoutWidget1)
        self.pbSelectAll.setObjectName(_fromUtf8("pbSelectAll"))
        self.horizontalLayout.addWidget(self.pbSelectAll)
        self.pbSelectNone = QtGui.QPushButton(self.layoutWidget1)
        self.pbSelectNone.setObjectName(_fromUtf8("pbSelectNone"))
        self.horizontalLayout.addWidget(self.pbSelectNone)
        self.pbInvertSelection = QtGui.QPushButton(self.layoutWidget1)
        self.pbInvertSelection.setObjectName(_fromUtf8("pbInvertSelection"))
        self.horizontalLayout.addWidget(self.pbInvertSelection)
        self.pbReadSpecFile = QtGui.QPushButton(self.layoutWidget1)
        self.pbReadSpecFile.setObjectName(_fromUtf8("pbReadSpecFile"))
        self.horizontalLayout.addWidget(self.pbReadSpecFile)
        self.vlFieldList.addLayout(self.horizontalLayout)
        self.chkSpecies = QtGui.QCheckBox(self.tab)
        self.chkSpecies.setGeometry(QtCore.QRect(10, 10, 251, 23))
        self.chkSpecies.setObjectName(_fromUtf8("chkSpecies"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.chkPlanningUnits = QtGui.QCheckBox(self.tab_2)
        self.chkPlanningUnits.setGeometry(QtCore.QRect(10, 10, 281, 23))
        self.chkPlanningUnits.setObjectName(_fromUtf8("chkPlanningUnits"))
        self.verticalLayoutWidget = QtGui.QWidget(self.tab_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 40, 671, 124))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.vlMeasureType = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.vlMeasureType.setMargin(0)
        self.vlMeasureType.setObjectName(_fromUtf8("vlMeasureType"))
        self.lblCostField = QtGui.QLabel(self.verticalLayoutWidget)
        self.lblCostField.setObjectName(_fromUtf8("lblCostField"))
        self.vlMeasureType.addWidget(self.lblCostField)
        self.cbxCostField = QtGui.QComboBox(self.verticalLayoutWidget)
        self.cbxCostField.setObjectName(_fromUtf8("cbxCostField"))
        self.vlMeasureType.addWidget(self.cbxCostField)
        self.lblStatusField = QtGui.QLabel(self.verticalLayoutWidget)
        self.lblStatusField.setObjectName(_fromUtf8("lblStatusField"))
        self.vlMeasureType.addWidget(self.lblStatusField)
        self.cbxStatusField = QtGui.QComboBox(self.verticalLayoutWidget)
        self.cbxStatusField.setObjectName(_fromUtf8("cbxStatusField"))
        self.vlMeasureType.addWidget(self.cbxStatusField)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.verticalLayoutWidget_4 = QtGui.QWidget(self.tab_3)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(10, 40, 671, 80))
        self.verticalLayoutWidget_4.setObjectName(_fromUtf8("verticalLayoutWidget_4"))
        self.vlSpeciesScale = QtGui.QVBoxLayout(self.verticalLayoutWidget_4)
        self.vlSpeciesScale.setMargin(0)
        self.vlSpeciesScale.setObjectName(_fromUtf8("vlSpeciesScale"))
        self.lblScaleOutput = QtGui.QLabel(self.verticalLayoutWidget_4)
        self.lblScaleOutput.setObjectName(_fromUtf8("lblScaleOutput"))
        self.vlSpeciesScale.addWidget(self.lblScaleOutput)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.rdoRaw = QtGui.QRadioButton(self.verticalLayoutWidget_4)
        self.rdoRaw.setObjectName(_fromUtf8("rdoRaw"))
        self.horizontalLayout_4.addWidget(self.rdoRaw)
        self.rdoScale = QtGui.QRadioButton(self.verticalLayoutWidget_4)
        self.rdoScale.setChecked(True)
        self.rdoScale.setObjectName(_fromUtf8("rdoScale"))
        self.horizontalLayout_4.addWidget(self.rdoScale)
        self.vlSpeciesScale.addLayout(self.horizontalLayout_4)
        self.chkPUvsSPC = QtGui.QCheckBox(self.tab_3)
        self.chkPUvsSPC.setGeometry(QtCore.QRect(10, 10, 581, 23))
        self.chkPUvsSPC.setObjectName(_fromUtf8("chkPUvsSPC"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.verticalLayoutWidget_5 = QtGui.QWidget(self.tab_4)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(10, 20, 671, 153))
        self.verticalLayoutWidget_5.setObjectName(_fromUtf8("verticalLayoutWidget_5"))
        self.vlBoundaryAction = QtGui.QVBoxLayout(self.verticalLayoutWidget_5)
        self.vlBoundaryAction.setMargin(0)
        self.vlBoundaryAction.setObjectName(_fromUtf8("vlBoundaryAction"))
        self.chkBoundary = QtGui.QCheckBox(self.verticalLayoutWidget_5)
        self.chkBoundary.setObjectName(_fromUtf8("chkBoundary"))
        self.vlBoundaryAction.addWidget(self.chkBoundary)
        self.lblBoundary = QtGui.QLabel(self.verticalLayoutWidget_5)
        self.lblBoundary.setObjectName(_fromUtf8("lblBoundary"))
        self.vlBoundaryAction.addWidget(self.lblBoundary)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.rdoLength = QtGui.QRadioButton(self.verticalLayoutWidget_5)
        self.rdoLength.setChecked(True)
        self.rdoLength.setObjectName(_fromUtf8("rdoLength"))
        self.horizontalLayout_3.addWidget(self.rdoLength)
        self.rdoLengthnField = QtGui.QRadioButton(self.verticalLayoutWidget_5)
        self.rdoLengthnField.setChecked(False)
        self.rdoLengthnField.setObjectName(_fromUtf8("rdoLengthnField"))
        self.horizontalLayout_3.addWidget(self.rdoLengthnField)
        self.rdoField = QtGui.QRadioButton(self.verticalLayoutWidget_5)
        self.rdoField.setObjectName(_fromUtf8("rdoField"))
        self.horizontalLayout_3.addWidget(self.rdoField)
        self.vlBoundaryAction.addLayout(self.horizontalLayout_3)
        self.lblBoundaryCost = QtGui.QLabel(self.verticalLayoutWidget_5)
        self.lblBoundaryCost.setEnabled(False)
        self.lblBoundaryCost.setObjectName(_fromUtf8("lblBoundaryCost"))
        self.vlBoundaryAction.addWidget(self.lblBoundaryCost)
        self.cbxBoundaryCost = QtGui.QComboBox(self.verticalLayoutWidget_5)
        self.cbxBoundaryCost.setEnabled(False)
        self.cbxBoundaryCost.setObjectName(_fromUtf8("cbxBoundaryCost"))
        self.vlBoundaryAction.addWidget(self.cbxBoundaryCost)
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.tab_4)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 180, 671, 61))
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self.vlCostAction = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.vlCostAction.setMargin(0)
        self.vlCostAction.setObjectName(_fromUtf8("vlCostAction"))
        self.lblBoundaryAction = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.lblBoundaryAction.setObjectName(_fromUtf8("lblBoundaryAction"))
        self.vlCostAction.addWidget(self.lblBoundaryAction)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.rdoAverage = QtGui.QRadioButton(self.verticalLayoutWidget_3)
        self.rdoAverage.setChecked(True)
        self.rdoAverage.setObjectName(_fromUtf8("rdoAverage"))
        self.horizontalLayout_2.addWidget(self.rdoAverage)
        self.rdoGreatest = QtGui.QRadioButton(self.verticalLayoutWidget_3)
        self.rdoGreatest.setObjectName(_fromUtf8("rdoGreatest"))
        self.horizontalLayout_2.addWidget(self.rdoGreatest)
        self.rdoLeast = QtGui.QRadioButton(self.verticalLayoutWidget_3)
        self.rdoLeast.setObjectName(_fromUtf8("rdoLeast"))
        self.horizontalLayout_2.addWidget(self.rdoLeast)
        self.vlCostAction.addLayout(self.horizontalLayout_2)
        self.verticalLayoutWidget_7 = QtGui.QWidget(self.tab_4)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(10, 260, 671, 80))
        self.verticalLayoutWidget_7.setObjectName(_fromUtf8("verticalLayoutWidget_7"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.lblTolerance = QtGui.QLabel(self.verticalLayoutWidget_7)
        self.lblTolerance.setObjectName(_fromUtf8("lblTolerance"))
        self.verticalLayout_2.addWidget(self.lblTolerance)
        self.cbxTolerance = QtGui.QComboBox(self.verticalLayoutWidget_7)
        self.cbxTolerance.setObjectName(_fromUtf8("cbxTolerance"))
        self.verticalLayout_2.addWidget(self.cbxTolerance)
        self.line = QtGui.QFrame(self.tab_4)
        self.line.setGeometry(QtCore.QRect(10, 160, 671, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(self.tab_4)
        self.line_2.setGeometry(QtCore.QRect(10, 240, 671, 16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.line_3 = QtGui.QFrame(self.tab_4)
        self.line_3.setGeometry(QtCore.QRect(10, 340, 671, 16))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayoutWidget_6 = QtGui.QWidget(self.tab_4)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(10, 360, 671, 61))
        self.verticalLayoutWidget_6.setObjectName(_fromUtf8("verticalLayoutWidget_6"))
        self.vlBorderAction = QtGui.QVBoxLayout(self.verticalLayoutWidget_6)
        self.vlBorderAction.setMargin(0)
        self.vlBorderAction.setObjectName(_fromUtf8("vlBorderAction"))
        self.lblBorderAction = QtGui.QLabel(self.verticalLayoutWidget_6)
        self.lblBorderAction.setObjectName(_fromUtf8("lblBorderAction"))
        self.vlBorderAction.addWidget(self.lblBorderAction)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.rdoFullValue = QtGui.QRadioButton(self.verticalLayoutWidget_6)
        self.rdoFullValue.setChecked(True)
        self.rdoFullValue.setObjectName(_fromUtf8("rdoFullValue"))
        self.horizontalLayout_7.addWidget(self.rdoFullValue)
        self.rdoHalfValue = QtGui.QRadioButton(self.verticalLayoutWidget_6)
        self.rdoHalfValue.setObjectName(_fromUtf8("rdoHalfValue"))
        self.horizontalLayout_7.addWidget(self.rdoHalfValue)
        self.rdoNone = QtGui.QRadioButton(self.verticalLayoutWidget_6)
        self.rdoNone.setChecked(False)
        self.rdoNone.setObjectName(_fromUtf8("rdoNone"))
        self.horizontalLayout_7.addWidget(self.rdoNone)
        self.vlBorderAction.addLayout(self.horizontalLayout_7)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.horizontalLayoutWidget = QtGui.QWidget(qm_export)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 701, 62))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.vlPlanningGrid = QtGui.QVBoxLayout()
        self.vlPlanningGrid.setObjectName(_fromUtf8("vlPlanningGrid"))
        self.lblPlanningGrid = QtGui.QLabel(self.horizontalLayoutWidget)
        self.lblPlanningGrid.setObjectName(_fromUtf8("lblPlanningGrid"))
        self.vlPlanningGrid.addWidget(self.lblPlanningGrid)
        self.cbxPlanningGrid = QtGui.QComboBox(self.horizontalLayoutWidget)
        self.cbxPlanningGrid.setObjectName(_fromUtf8("cbxPlanningGrid"))
        self.vlPlanningGrid.addWidget(self.cbxPlanningGrid)
        self.horizontalLayout_5.addLayout(self.vlPlanningGrid)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.lbIdField = QtGui.QLabel(self.horizontalLayoutWidget)
        self.lbIdField.setObjectName(_fromUtf8("lbIdField"))
        self.verticalLayout.addWidget(self.lbIdField)
        self.cbxIdField = QtGui.QComboBox(self.horizontalLayoutWidget)
        self.cbxIdField.setObjectName(_fromUtf8("cbxIdField"))
        self.verticalLayout.addWidget(self.cbxIdField)
        self.horizontalLayout_5.addLayout(self.verticalLayout)

        self.retranslateUi(qm_export)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), qm_export.reject)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), qm_export.accept)
        QtCore.QMetaObject.connectSlotsByName(qm_export)

    def retranslateUi(self, qm_export):
        qm_export.setWindowTitle(QtGui.QApplication.translate("qm_export", "Create Marxan Input Files", None, QtGui.QApplication.UnicodeUTF8))
        self.lblOutputDirectory.setText(QtGui.QApplication.translate("qm_export", "Select Marxan scenario input directory", None, QtGui.QApplication.UnicodeUTF8))
        self.pbOutputDir.setText(QtGui.QApplication.translate("qm_export", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.twFields.setSortingEnabled(False)
        self.pbSelectAll.setText(QtGui.QApplication.translate("qm_export", "Check All", None, QtGui.QApplication.UnicodeUTF8))
        self.pbSelectNone.setText(QtGui.QApplication.translate("qm_export", "Check None", None, QtGui.QApplication.UnicodeUTF8))
        self.pbInvertSelection.setText(QtGui.QApplication.translate("qm_export", "Invert Checks", None, QtGui.QApplication.UnicodeUTF8))
        self.pbReadSpecFile.setText(QtGui.QApplication.translate("qm_export", "Read Spec File", None, QtGui.QApplication.UnicodeUTF8))
        self.chkSpecies.setText(QtGui.QApplication.translate("qm_export", "Create Species File (spec.dat)", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("qm_export", "spec.dat", None, QtGui.QApplication.UnicodeUTF8))
        self.chkPlanningUnits.setText(QtGui.QApplication.translate("qm_export", "Create Planning Units File (pu.dat)", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCostField.setText(QtGui.QApplication.translate("qm_export", "Planning Unit Cost Field", None, QtGui.QApplication.UnicodeUTF8))
        self.lblStatusField.setText(QtGui.QApplication.translate("qm_export", "Planning Unit Initial Status Field", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("qm_export", "pu.dat", None, QtGui.QApplication.UnicodeUTF8))
        self.lblScaleOutput.setText(QtGui.QApplication.translate("qm_export", "Scale species data from 0 to 1", None, QtGui.QApplication.UnicodeUTF8))
        self.rdoRaw.setText(QtGui.QApplication.translate("qm_export", "Raw", None, QtGui.QApplication.UnicodeUTF8))
        self.rdoScale.setText(QtGui.QApplication.translate("qm_export", "Scaled", None, QtGui.QApplication.UnicodeUTF8))
        self.chkPUvsSPC.setText(QtGui.QApplication.translate("qm_export", "Create Planning Units vs Species Files (puvspr.dat and puvspr_sporder.dat)", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("qm_export", "puvspr.dat", None, QtGui.QApplication.UnicodeUTF8))
        self.chkBoundary.setText(QtGui.QApplication.translate("qm_export", "Boundary File (bound.dat)", None, QtGui.QApplication.UnicodeUTF8))
        self.lblBoundary.setText(QtGui.QApplication.translate("qm_export", "Set boundary cost using the:", None, QtGui.QApplication.UnicodeUTF8))
        self.rdoLength.setText(QtGui.QApplication.translate("qm_export", "Length", None, QtGui.QApplication.UnicodeUTF8))
        self.rdoLengthnField.setText(QtGui.QApplication.translate("qm_export", "Length x Field", None, QtGui.QApplication.UnicodeUTF8))
        self.rdoField.setText(QtGui.QApplication.translate("qm_export", "Field", None, QtGui.QApplication.UnicodeUTF8))
        self.lblBoundaryCost.setText(QtGui.QApplication.translate("qm_export", "Boundary Cost Field", None, QtGui.QApplication.UnicodeUTF8))
        self.lblBoundaryAction.setText(QtGui.QApplication.translate("qm_export", "When boundary costs differ (using field values) assign the value that is the:", None, QtGui.QApplication.UnicodeUTF8))
        self.rdoAverage.setText(QtGui.QApplication.translate("qm_export", "Average", None, QtGui.QApplication.UnicodeUTF8))
        self.rdoGreatest.setText(QtGui.QApplication.translate("qm_export", "Greatest", None, QtGui.QApplication.UnicodeUTF8))
        self.rdoLeast.setText(QtGui.QApplication.translate("qm_export", "Least", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTolerance.setText(QtGui.QApplication.translate("qm_export", "The spatial tolerance in projection units for identifying adjacent areas is:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblBorderAction.setText(QtGui.QApplication.translate("qm_export", "The boundary cost value for planning units at edge of planning space is:", None, QtGui.QApplication.UnicodeUTF8))
        self.rdoFullValue.setText(QtGui.QApplication.translate("qm_export", "Full Value", None, QtGui.QApplication.UnicodeUTF8))
        self.rdoHalfValue.setText(QtGui.QApplication.translate("qm_export", "Half Value", None, QtGui.QApplication.UnicodeUTF8))
        self.rdoNone.setText(QtGui.QApplication.translate("qm_export", "No value (remove)", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("qm_export", "bound.dat", None, QtGui.QApplication.UnicodeUTF8))
        self.lblPlanningGrid.setText(QtGui.QApplication.translate("qm_export", "Select Planning Grid", None, QtGui.QApplication.UnicodeUTF8))
        self.lbIdField.setText(QtGui.QApplication.translate("qm_export", "Planning Unit Id Field", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
